# Kindle Sequential Recommendation: Tuned SASRec and GRU4Rec

This notebook trains and evaluates:

1. **Popularity** - a non-personalised reference baseline.
2. **First-order Markov** - a simple sequential baseline using the last observed item.
3. **Tuned SASRec** - a causal Transformer for next-item prediction.
4. **GRU4Rec** - a recurrent next-item model for short histories.

The protocol is fixed throughout:

- interactions rated below 4 have already been removed by preprocessing;
- training uses only prefixes of `train_sequences.csv`;
- validation predicts `val.pos_idx` from the complete training sequence;
- testing predicts `test.pos_idx` from the training sequence **plus the validation item**;
- every target is ranked against its 100 fixed negatives;
- test targets never enter training inputs, training loss, model selection, or hyperparameter tuning;
- raw item indices start at 0, while model-side indices are shifted by +1 so that 0 remains padding.

With one relevant item per candidate set, `Recall@10` and `Hit@10` are numerically identical. Both labels are reported for compatibility. The offline candidate-set results do not measure catalogue-wide retrieval or post-deployment user impact.

## 1. Setup and configuration

Set `DATA_DIR` to the folder containing the nine prepared files. Defaults are deliberately small because the median training history is short. For a final run, keep the seed fixed and select epochs only with validation NDCG@10.

Required packages are `numpy`, `pandas`, and `torch`. If the environment does not provide them, install them in a separate setup cell (for example, `%pip install numpy pandas torch`) and restart the kernel before importing.

In [1]:
from __future__ import annotations

import ast
import copy
import json
import math
import random
import re
import time
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset


@dataclass
class Config:
    data_dir: Path = Path("data")
    max_len: int = 50
    hidden_dim: int = 64
    num_blocks: int = 2
    num_heads: int = 2
    dropout: float = 0.20
    batch_size: int = 256
    learning_rate: float = 1e-3
    weight_decay: float = 0.0
    max_epochs: int = 30
    patience: int = 4
    eval_batch_size: int = 512
    num_workers: int = 0
    seed: int = 2026
    top_k: int = 10
    min_delta: float = 1e-5


CFG = Config()
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


seed_everything(CFG.seed)
print("device:", DEVICE)
print(CFG)

device: cuda
Config(data_dir=WindowsPath('data'), max_len=50, hidden_dim=64, num_blocks=2, num_heads=2, dropout=0.2, batch_size=256, learning_rate=0.001, weight_decay=0.0, max_epochs=30, patience=4, eval_batch_size=512, num_workers=0, seed=2026, top_k=10, min_delta=1e-05)

## 2. Load files and normalise schemas

The loaders accept common column-name variants and sequence encodings such as JSON lists, Python-style lists, or delimiter-separated integers. Ambiguous or malformed schemas raise an error instead of guessing silently.

In [2]:
# Use the prepared Kindle data whether this notebook is run from proj2/ or the repository root.
DATA_DIR_CANDIDATES = (Path("processed_kindle"), Path("proj2/processed_kindle"))
CFG.data_dir = next((path for path in DATA_DIR_CANDIDATES if path.is_dir()), DATA_DIR_CANDIDATES[0])
print("data directory:", CFG.data_dir.resolve())

data directory: D:\unsw\COMP9727\proj2\processed_kindle

In [3]:
REQUIRED_FILES = [
    "train_sequences.csv", "train_triplets.csv", "val.csv", "test.csv",
    "val_negatives.csv", "test_negatives.csv", "item_metadata.csv",
    "preprocess_config.json", "preprocess_stats.json",
]


def require_files(data_dir: Path) -> None:
    missing = [name for name in REQUIRED_FILES if not (data_dir / name).exists()]
    if missing:
        raise FileNotFoundError(
            f"Missing {len(missing)} required file(s) under {data_dir.resolve()}: {missing}"
        )


def choose_col(df: pd.DataFrame, candidates: Sequence[str], purpose: str) -> str:
    hits = [c for c in candidates if c in df.columns]
    if len(hits) != 1:
        raise ValueError(
            f"Expected exactly one {purpose} column from {list(candidates)}; "
            f"found {hits}. Available columns: {df.columns.tolist()}"
        )
    return hits[0]


def parse_int_list(value) -> List[int]:
    if isinstance(value, (list, tuple, np.ndarray)):
        values = list(value)
    elif pd.isna(value):
        values = []
    else:
        text = str(value).strip()
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            try:
                parsed = ast.literal_eval(text)
            except (ValueError, SyntaxError):
                parsed = [x for x in re.split(r"[\s,;|]+", text.strip("[]()")) if x]
        values = list(parsed) if isinstance(parsed, (list, tuple, np.ndarray)) else [parsed]
    try:
        return [int(x) for x in values]
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Cannot parse an integer list from {value!r}") from exc


def read_sequences(path: Path) -> Tuple[Dict[int, List[int]], pd.DataFrame]:
    df = pd.read_csv(path)
    user_col = choose_col(df, ["user_idx", "user_id", "user"], "user")
    seq_col = choose_col(df, ["item_seq", "sequence", "items"], "sequence")
    if df[user_col].duplicated().any():
        raise ValueError(f"{path.name} contains duplicate user rows")
    sequences = {
        int(user): parse_int_list(seq)
        for user, seq in zip(df[user_col], df[seq_col])
    }
    return sequences, df


def read_targets(path: Path) -> Tuple[Dict[int, int], pd.DataFrame]:
    df = pd.read_csv(path)
    user_col = choose_col(df, ["user_idx", "user_id", "user"], "user")
    item_col = choose_col(df, ["pos_idx", "item_idx", "item_id", "item"], "positive item")
    if df[user_col].duplicated().any():
        raise ValueError(f"{path.name} contains duplicate user rows")
    return dict(zip(df[user_col].astype(int), df[item_col].astype(int))), df


def read_negatives(path: Path) -> Tuple[Dict[int, List[int]], pd.DataFrame]:
    df = pd.read_csv(path)
    user_col = choose_col(df, ["user_idx", "user_id", "user"], "user")
    list_cols = [c for c in ["negatives", "negative_items", "neg_items", "neg_idx"] if c in df.columns]
    if list_cols:
        if len(list_cols) != 1 or df[user_col].duplicated().any():
            raise ValueError(f"Ambiguous or duplicate-row negative-list schema in {path.name}")
        result = {
            int(user): parse_int_list(items)
            for user, items in zip(df[user_col], df[list_cols[0]])
        }
    else:
        item_col = choose_col(
            df, ["negative_idx", "item_idx", "item_id", "item"], "negative item"
        )
        result = {
            int(user): group[item_col].astype(int).tolist()
            for user, group in df.groupby(user_col, sort=False)
        }
    return result, df


require_files(CFG.data_dir)
train_sequences, train_sequences_df = read_sequences(CFG.data_dir / "train_sequences.csv")
val_targets, val_df = read_targets(CFG.data_dir / "val.csv")
test_targets, test_df = read_targets(CFG.data_dir / "test.csv")
val_negatives, val_negatives_df = read_negatives(CFG.data_dir / "val_negatives.csv")
test_negatives, test_negatives_df = read_negatives(CFG.data_dir / "test_negatives.csv")
train_triplets_df = pd.read_csv(CFG.data_dir / "train_triplets.csv")
item_metadata_df = pd.read_csv(CFG.data_dir / "item_metadata.csv")

with open(CFG.data_dir / "preprocess_config.json", encoding="utf-8") as f:
    preprocess_config = json.load(f)
with open(CFG.data_dir / "preprocess_stats.json", encoding="utf-8") as f:
    preprocess_stats = json.load(f)

print("preprocess_config:", json.dumps(preprocess_config, indent=2, ensure_ascii=False))
print("preprocess_stats:", json.dumps(preprocess_stats, indent=2, ensure_ascii=False))
print(f"users={len(train_sequences):,}; train interactions={sum(map(len, train_sequences.values())):,}")

preprocess_config: {
  "reviews_path": "Kindle_Store.jsonl",
  "metadata_path": "meta_Kindle_Store.jsonl",
  "output_dir": "processed_kindle",
  "work_db_name": "preprocess_work.sqlite",
  "year_start": 2014,
  "year_end": 2022,
  "positive_threshold": 4.0,
  "deduplication": "keep_latest_user_item_interaction",
  "require_metadata_match": true,
  "min_user_positives": 5,
  "min_item_positives": 5,
  "filter_method": "iterative_5_core",
  "sample_strategy": "user_activity_stratified",
  "target_interactions": 1000000,
  "sample_overshoot_ratio": 1.62,
  "split": "chronological_leave_one_out",
  "ensure_eval_items_in_train": true,
  "default_num_negatives": 1,
  "negative_exclusion": "all_user_positive_items",
  "negative_unique_per_positive": true,
  "eval_num_negatives": 100,
  "missing_verified_purchase": false,
  "remove_categories": [
    "Kindle Store",
    "Kindle eBooks"
  ],
  "split_inner_category": true,
  "write_sequence_side_fields": true,
  "random_seed": 42,
  "progress_every": 200000,
  "sqlite_commit_every": 50000,
  "overwrite": true
}
preprocess_stats: {
  "metadata_lines_read": 1591371,
  "metadata_invalid_lines": 0,
  "metadata_rows_accepted_before_dedup": 1591371,
  "metadata_unique_items": 1591371,
  "review_lines_read": 25577616,
  "review_invalid_lines": 0,
  "review_lines_outside_year_range": 3394726,
  "review_rows_accepted_before_dedup": 22182890,
  "unique_user_item_pairs_after_latest_dedup": 21949983,
  "interactions_before_positive_filter": 21949983,
  "positive_interactions_after_rating_filter": 19036301,
  "positive_interactions_after_metadata_match": 19036301,
  "first_5_core_rounds": 8,
  "first_5_core_history": [
    {
      "round": 1,
      "before": 19036301,
      "after_user_filter": 12996777,
      "after_item_filter": 11894245
    },
    {
      "round": 2,
      "before": 11894245,
      "after_user_filter": 11653659,
      "after_item_filter": 11607061
    },
    {
      "round": 3,
      "before": 11607061,
      "after_user_filter": 11586567,
      "after_item_filter": 11581214
    },
    {
      "round": 4,
      "before": 11581214,
      "after_user_filter": 11578421,
      "after_item_filter": 11577463
    },
    {
      "round": 5,
      "before": 11577463,
      "after_user_filter": 11576904,
      "after_item_filter": 11576673
    },
    {
      "round": 6,
      "before": 11576673,
      "after_user_filter": 11576563,
      "after_item_filter": 11576515
    },
    {
      "round": 7,
      "before": 11576515,
      "after_user_filter": 11576507,
      "after_item_filter": 11576507
    },
    {
      "round": 8,
      "before": 11576507,
      "after_user_filter": 11576507,
      "after_item_filter": 11576507
    }
  ],
  "first_5_core_final_interactions": 11576507,
  "first_5_core_final_users": 630729,
  "first_5_core_final_items": 372359,
  "interactions_before_user_sampling": 11576507,
  "sampling_target_interactions": 1000000,
  "sampling_overshoot_target": 1620000,
  "sampling_applied": true,
  "sampled_users_before_second_core": 88249,
  "sampled_interactions_before_second_core": 1619999,
  "second_5_core_rounds": 10,
  "second_5_core_history": [
    {
      "round": 1,
      "before": 1619999,
      "after_user_filter": 1619999,
      "after_item_filter": 1183656
    },
    {
      "round": 2,
      "before": 1183656,
      "after_user_filter": 1122749,
      "after_item_filter": 1101519
    },
    {
      "round": 3,
      "before": 1101519,
      "after_user_filter": 1094843,
      "after_item_filter": 1092240
    },
    {
      "round": 4,
      "before": 1092240,
      "after_user_filter": 1091313,
      "after_item_filter": 1090923
    },
    {
      "round": 5,
      "before": 1090923,
      "after_user_filter": 1090729,
      "after_item_filter": 1090622
    },
    {
      "round": 6,
      "before": 1090622,
      "after_user_filter": 1090570,
      "after_item_filter": 1090502
    },
    {
      "round": 7,
      "before": 1090502,
      "after_user_filter": 1090478,
      "after_item_filter": 1090454
    },
    {
      "round": 8,
      "before": 1090454,
      "after_user_filter": 1090450,
      "after_item_filter": 1090438
    },
    {
      "round": 9,
      "before": 1090438,
      "after_user_filter": 1090434,
      "after_item_filter": 1090430
    },
    {
      "round": 10,
      "before": 1090430,
      "after_user_filter": 1090430,
      "after_item_filter": 1090430
    }
  ],
  "second_5_core_final_interactions": 1090430,
  "second_5_core_final_users": 66261,
  "second_5_core_final_items": 81681,
  "users_loaded_for_split": 66261,
  "interactions_loaded_for_split": 1090430,
  "eval_train_coverage_filter_applied": true,
  "eval_train_coverage_rounds": 9,
  "users_removed_for_unseen_eval_items": 1394,
  "users_after_eval_train_coverage": 64867,
  "num_users": 64867,
  "num_items": 81322,
  "num_interactions": 1013870,
  "num_train_interactions": 884136,
  "num_validation_interactions": 64867,
  "num_test_interactions": 64867,
  "num_train_triplets": 884136,
  "metadata_rows_written": 81322,
  "eval_negative_files_written": true,
  "eval_num_negatives_per_user": 100,
  "positive_threshold": 4.0,
  "min_user_positives": 5,
  "min_item_positives": 5,
  "split": "chronological_leave_one_out",
  "sample_strategy": "user_activity_stratified",
  "random_seed": 42,
  "avg_full_sequence_length": 15.629981346447346,
  "median_full_sequence_length": 8,
  "min_full_sequence_length": 5,
  "max_full_sequence_length": 865,
  "avg_train_sequence_length": 13.629981346447346,
  "median_train_sequence_length": 6,
  "elapsed_seconds": 2885.74
}
users=64,867; train interactions=884,136

## 3. Protocol and leakage audit

These assertions verify the most consequential assumptions: aligned user sets, 100 distinct negatives, positive/negative separation, non-negative 0-based IDs, and absence of held-out positives from the training histories. A repeated item can be legitimate in raw review data, but under a leave-two-out item recommendation protocol it usually indicates a split or deduplication problem; inspect rather than bypass failures.

In [4]:
def audit_protocol() -> pd.DataFrame:
    users = set(train_sequences)
    sources = {
        "val targets": set(val_targets), "test targets": set(test_targets),
        "val negatives": set(val_negatives), "test negatives": set(test_negatives),
    }
    for name, source_users in sources.items():
        if source_users != users:
            raise AssertionError(
                f"User mismatch for {name}: missing={len(users-source_users)}, "
                f"extra={len(source_users-users)}"
            )

    all_ids = []
    failures = []
    for user in sorted(users):
        seq = train_sequences[user]
        vp, tp = val_targets[user], test_targets[user]
        vn, tn = val_negatives[user], test_negatives[user]
        all_ids.extend(seq + [vp, tp] + vn + tn)
        if len(vn) != 100 or len(set(vn)) != 100:
            failures.append((user, "validation negatives are not 100 distinct items"))
        if len(tn) != 100 or len(set(tn)) != 100:
            failures.append((user, "test negatives are not 100 distinct items"))
        if vp in vn or tp in tn:
            failures.append((user, "positive appears in its candidate negatives"))
        if vp in seq or tp in seq or tp == vp:
            failures.append((user, "held-out positive leaks/repeats across chronological splits"))
    if failures:
        raise AssertionError(f"Protocol audit failed; first examples: {failures[:10]}")
    if min(all_ids) < 0:
        raise AssertionError("Negative item index found")

    # Triplets are not used as an additional objective below, but their sampled labels
    # must still agree with the chronological train/holdout split.
    triplet_user_col = choose_col(train_triplets_df, ["user_idx", "user_id", "user"], "triplet user")
    triplet_pos_col = choose_col(
        train_triplets_df,
        ["pos_idx", "positive_idx", "pos_item_idx", "item_idx", "item_id", "item"],
        "triplet positive item",
    )
    triplet_neg_col = choose_col(
        train_triplets_df,
        ["neg_idx", "negative_idx", "neg_item_idx", "negative_item_idx"],
        "triplet negative item",
    )
    bad_triplets = []
    training_item_sets = {u: set(seq) for u, seq in train_sequences.items()}
    for row in train_triplets_df[[triplet_user_col, triplet_pos_col, triplet_neg_col]].itertuples(index=False, name=None):
        user, positive, negative = map(int, row)
        if user not in train_sequences:
            bad_triplets.append((user, positive, negative, "unknown user"))
            continue
        if positive not in training_item_sets[user]:
            bad_triplets.append((user, positive, negative, "positive is outside training sequence"))
        if positive == negative or negative in training_item_sets[user]:
            bad_triplets.append((user, positive, negative, "invalid/observed negative"))
        if negative in {val_targets[user], test_targets[user]}:
            bad_triplets.append((user, positive, negative, "negative is a held-out positive"))
        if len(bad_triplets) >= 10:
            break
    if bad_triplets:
        raise AssertionError(f"Triplet audit failed; first examples: {bad_triplets}")

    lengths = pd.Series([len(x) for x in train_sequences.values()], name="train_length")
    summary = lengths.describe(percentiles=[.25, .5, .75, .9, .95, .99]).to_frame()
    print("raw item ID range:", (min(all_ids), max(all_ids)))
    print("candidate protocol: 1 positive + 100 fixed negatives per user")
    return summary


audit_protocol()

raw item ID range: (0, 81321)
candidate protocol: 1 positive + 100 fixed negatives per user

       train_length
count  64867.000000
mean      13.629981
std       29.876118
min        3.000000
25%        4.000000
50%        6.000000
75%       12.000000
90%       26.000000
95%       45.000000
99%      143.000000
max      863.000000

In [5]:
# Infer the embedding vocabulary from every split/candidate file, not metadata row count.
max_item_id = max(
    max(max(seq, default=-1) for seq in train_sequences.values()),
    max(val_targets.values()), max(test_targets.values()),
    max(max(x) for x in val_negatives.values()),
    max(max(x) for x in test_negatives.values()),
)
NUM_ITEMS = max_item_id + 1  # number of real, raw 0-based items
PAD_ID = 0                  # model-side padding ID


def to_model_id(raw_item_id: int) -> int:
    return int(raw_item_id) + 1


print(f"NUM_ITEMS={NUM_ITEMS:,}; embedding rows={NUM_ITEMS + 1:,} (including padding)")

NUM_ITEMS=81,322; embedding rows=81,323 (including padding)

## 4. Shared evaluation

The same evaluator is used for all models. Candidate order is deterministically shuffled per user before sorting, so tied scores do not systematically favour the positive item. MRR is computed over all 101 candidates; Hit, Recall, Precision and NDCG use the requested cutoff of 10. Because each candidate set has exactly one relevant item, Recall@10 equals Hit@10 and Precision@10 equals Hit@10 divided by 10. CandidateAccuracy@10 is reported only for compatibility with classification-style reporting: its 101-way class imbalance makes it much less informative than NDCG, Recall and MRR.

In [6]:
def rank_from_scores(
    user: int, candidates: Sequence[int], scores: Sequence[float], seed: int
) -> int:
    candidates = np.asarray(candidates, dtype=np.int64)
    scores = np.asarray(scores, dtype=np.float64)
    if len(candidates) != len(scores):
        raise ValueError("Candidate and score lengths differ")
    rng = np.random.default_rng(seed + int(user))
    perm = rng.permutation(len(candidates))
    shuffled_scores = scores[perm]
    shuffled_positive_position = int(np.flatnonzero(perm == 0)[0])
    order = np.argsort(-shuffled_scores, kind="stable")
    return int(np.flatnonzero(order == shuffled_positive_position)[0]) + 1


def summarise_ranks(ranks: Sequence[int], k: int = 10, num_candidates: int = 101) -> Dict[str, float]:
    ranks = np.asarray(ranks, dtype=np.int64)
    hits = ranks <= k
    hit = float(hits.mean())
    if not 0 < k < num_candidates:
        raise ValueError("k must be between 1 and num_candidates - 1")
    # Classifying the Top-k as positive produces k predictions per 101-item set.
    # It is included only when a classification-style accuracy is explicitly required.
    candidate_accuracy = float((num_candidates - k + hit) / num_candidates)
    return {
        f"Hit@{k}": hit,
        f"Recall@{k}": hit,
        f"Precision@{k}": hit / k,
        f"CandidateAccuracy@{k}": candidate_accuracy,
        f"NDCG@{k}": float(np.where(hits, 1.0 / np.log2(ranks + 1), 0.0).mean()),
        "MRR": float((1.0 / ranks).mean()),
        "users": int(len(ranks)),
    }


def evaluate_score_function(
    contexts: Mapping[int, Sequence[int]],
    targets: Mapping[int, int],
    negatives: Mapping[int, Sequence[int]],
    score_fn,
    k: int = 10,
) -> Dict[str, float]:
    ranks = []
    for user in sorted(targets):
        candidates = [targets[user], *negatives[user]]
        scores = score_fn(user, contexts[user], candidates)
        ranks.append(rank_from_scores(user, candidates, scores, CFG.seed))
    return summarise_ranks(ranks, k)


val_contexts = train_sequences
test_contexts = {u: train_sequences[u] + [val_targets[u]] for u in train_sequences}

## 5. Baselines

Popularity counts only training interactions. The Markov model counts adjacent training transitions and uses global popularity as a small backoff/tie-breaker. It never learns from validation or test transitions.

In [7]:
popularity = np.zeros(NUM_ITEMS, dtype=np.int64)
transition_counts: Dict[int, Counter] = defaultdict(Counter)

for seq in train_sequences.values():
    for item in seq:
        popularity[item] += 1
    for previous, nxt in zip(seq[:-1], seq[1:]):
        transition_counts[previous][nxt] += 1

popularity_scaled = np.log1p(popularity) / max(np.log1p(popularity).max(), 1.0)


def popularity_score(user, context, candidates):
    return popularity_scaled[np.asarray(candidates)]


def markov_score(user, context, candidates):
    candidates = np.asarray(candidates)
    if not context:
        return popularity_scaled[candidates]
    outgoing = transition_counts.get(context[-1], {})
    transition = np.asarray([outgoing.get(int(item), 0) for item in candidates], dtype=float)
    return transition + 1e-3 * popularity_scaled[candidates]


baseline_rows = []
for name, scorer in [("Popularity", popularity_score), ("Markov-1", markov_score)]:
    val_metrics = evaluate_score_function(val_contexts, val_targets, val_negatives, scorer, CFG.top_k)
    test_metrics = evaluate_score_function(test_contexts, test_targets, test_negatives, scorer, CFG.top_k)
    baseline_rows.extend([
        {"model": name, "split": "validation", **val_metrics},
        {"model": name, "split": "test", **test_metrics},
    ])

baseline_results = pd.DataFrame(baseline_rows)
baseline_results

,model,split,Hit@10,Recall@10,Precision@10,CandidateAccuracy@10,NDCG@10,MRR,users
0,Popularity,validation,0.405645,0.405645,0.040565,0.905006,0.253269,0.224836,64867
1,Popularity,test,0.375121,0.375121,0.037512,0.904704,0.232436,0.206891,64867
2,Markov-1,validation,0.456827,0.456827,0.045683,0.905513,0.320822,0.295560,64867
3,Markov-1,test,0.417115,0.417115,0.041712,0.905120,0.288026,0.265202,64867

## 6. Prefix-to-next-item training data

For a training sequence `[i1, i2, i3]`, SASRec receives `[i1, i2]` and predicts `[i2, i3]` position-wise. One unobserved negative is sampled for each non-padding target. This is sampled binary cross-entropy, closely matching the original SASRec objective; `train_triplets.csv` is retained for preprocessing audit but is not mixed into a second, incompatible sampling scheme.

In [8]:
class SASRecTrainDataset(Dataset):
    def __init__(self, sequences: Mapping[int, Sequence[int]], num_items: int, max_len: int):
        self.users = [u for u, seq in sequences.items() if len(seq) >= 2]
        self.sequences = sequences
        self.num_items = num_items
        self.max_len = max_len
        self.seen = {u: set(seq) for u, seq in sequences.items()}

    def __len__(self) -> int:
        return len(self.users)

    def _negative(self, seen: set) -> int:
        if len(seen) >= self.num_items:
            raise RuntimeError("Cannot sample an unseen item for this user")
        item = np.random.randint(0, self.num_items)
        while item in seen:
            item = np.random.randint(0, self.num_items)
        return item

    def __getitem__(self, index: int):
        user = self.users[index]
        seq = self.sequences[user]
        raw_inputs = seq[:-1][-self.max_len:]
        raw_positives = seq[1:][-self.max_len:]
        n = len(raw_inputs)

        inputs = np.zeros(self.max_len, dtype=np.int64)
        positives = np.zeros(self.max_len, dtype=np.int64)
        negatives = np.zeros(self.max_len, dtype=np.int64)
        inputs[-n:] = np.asarray(raw_inputs) + 1
        positives[-n:] = np.asarray(raw_positives) + 1
        negatives[-n:] = np.asarray([self._negative(self.seen[user]) for _ in range(n)]) + 1
        return (
            torch.from_numpy(inputs),
            torch.from_numpy(positives),
            torch.from_numpy(negatives),
        )


train_dataset = SASRecTrainDataset(train_sequences, NUM_ITEMS, CFG.max_len)
train_loader = DataLoader(
    train_dataset,
    batch_size=CFG.batch_size,
    shuffle=True,
    num_workers=CFG.num_workers,
    pin_memory=torch.cuda.is_available(),
)
print(f"training users with >=2 items: {len(train_dataset):,}")

training users with >=2 items: 64,867

In [9]:
# Keep held-out positives out of the sampled-negative pool.  They remain absent from
# training inputs and positive loss labels, but cannot be incorrectly labelled negative.
held_out_positives = {user: {val_targets[user], test_targets[user]} for user in train_sequences}
train_dataset.seen = {
    user: set(sequence).union(held_out_positives[user])
    for user, sequence in train_sequences.items()
}
print("negative-sampling exclusions include train, validation, and test positives")

negative-sampling exclusions include train, validation, and test positives

## 7. SASRec-lite model

The causal attention mask prevents every position from reading future items. Padding is masked separately. The final non-padding position represents the context for candidate scoring. The item embedding matrix is shared between sequence encoding and output scoring.

In [10]:
class SASRec(nn.Module):
    def __init__(
        self,
        num_items: int,
        max_len: int,
        hidden_dim: int = 64,
        num_blocks: int = 2,
        num_heads: int = 2,
        dropout: float = 0.2,
    ):
        super().__init__()
        self.max_len = max_len
        self.hidden_dim = hidden_dim
        self.item_embedding = nn.Embedding(num_items + 1, hidden_dim, padding_idx=0)
        self.position_embedding = nn.Embedding(max_len, hidden_dim)
        self.dropout = nn.Dropout(dropout)
        layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=num_heads,
            dim_feedforward=hidden_dim * 4,
            dropout=dropout,
            activation="gelu",
            batch_first=True,
            norm_first=True,
        )
        self.encoder = nn.TransformerEncoder(layer, num_layers=num_blocks)
        self.final_norm = nn.LayerNorm(hidden_dim)
        self.apply(self._init_weights)
        with torch.no_grad():
            self.item_embedding.weight[0].zero_()

    @staticmethod
    def _init_weights(module):
        if isinstance(module, (nn.Linear, nn.Embedding)):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)
        if isinstance(module, nn.Linear) and module.bias is not None:
            nn.init.zeros_(module.bias)

    def encode(self, item_ids: torch.Tensor) -> torch.Tensor:
        batch_size, seq_len = item_ids.shape
        if seq_len != self.max_len:
            raise ValueError(f"Expected sequence length {self.max_len}, got {seq_len}")
        positions = torch.arange(seq_len, device=item_ids.device).unsqueeze(0)
        x = self.item_embedding(item_ids) * math.sqrt(self.hidden_dim)
        x = self.dropout(x + self.position_embedding(positions))
        padding_mask = item_ids.eq(0)
        causal_mask = torch.triu(
            torch.ones(seq_len, seq_len, device=item_ids.device, dtype=torch.bool),
            diagonal=1,
        )
        x = self.encoder(x, mask=causal_mask, src_key_padding_mask=padding_mask)
        return self.final_norm(x)

    def forward(self, item_ids: torch.Tensor) -> torch.Tensor:
        return self.encode(item_ids)

    def score_candidates(self, item_ids: torch.Tensor, candidate_ids: torch.Tensor) -> torch.Tensor:
        features = self.encode(item_ids)
        lengths = item_ids.ne(0).sum(dim=1).clamp_min(1)
        # Inputs are left padded, so the last array position is the final observed item.
        context_features = features[:, -1, :]
        candidate_embeddings = self.item_embedding(candidate_ids)
        return torch.einsum("bd,bcd->bc", context_features, candidate_embeddings)


model = SASRec(
    num_items=NUM_ITEMS,
    max_len=CFG.max_len,
    hidden_dim=CFG.hidden_dim,
    num_blocks=CFG.num_blocks,
    num_heads=CFG.num_heads,
    dropout=CFG.dropout,
).to(DEVICE)
print(f"parameters: {sum(p.numel() for p in model.parameters()):,}")

parameters: 5,307,968

C:\Users\al\AppData\Local\Temp\ipykernel_45112\1547733667.py:26: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.encoder = nn.TransformerEncoder(layer, num_layers=num_blocks)

## 8. Batched SASRec evaluation

Only validation metrics are used inside the training loop. The test evaluator is called once after restoring the best validation checkpoint.

In [11]:
def left_pad_context(context: Sequence[int], max_len: int) -> np.ndarray:
    context = list(context)[-max_len:]
    result = np.zeros(max_len, dtype=np.int64)
    if context:
        result[-len(context):] = np.asarray(context, dtype=np.int64) + 1
    return result


@torch.no_grad()
def evaluate_sasrec(
    model: SASRec,
    contexts: Mapping[int, Sequence[int]],
    targets: Mapping[int, int],
    negatives: Mapping[int, Sequence[int]],
    batch_size: int = 512,
    k: int = 10,
) -> Dict[str, float]:
    model.eval()
    users = sorted(targets)
    ranks = []
    for start in range(0, len(users), batch_size):
        batch_users = users[start:start + batch_size]
        input_np = np.stack([left_pad_context(contexts[u], CFG.max_len) for u in batch_users])
        candidate_np = np.asarray(
            [[targets[u], *negatives[u]] for u in batch_users], dtype=np.int64
        )
        input_tensor = torch.as_tensor(input_np, device=DEVICE)
        candidate_tensor = torch.as_tensor(candidate_np + 1, device=DEVICE)
        scores = model.score_candidates(input_tensor, candidate_tensor).cpu().numpy()
        for row, user in enumerate(batch_users):
            ranks.append(rank_from_scores(user, candidate_np[row], scores[row], CFG.seed))
    return summarise_ranks(ranks, k)

## 9. Train with validation NDCG@10 early stopping

Loss is averaged only over real target positions. The best in-memory state is selected by validation NDCG@10. For long experiments, optionally save `best_state` after training; do not select a checkpoint using test results.

In [12]:
def train_sasrec(model: SASRec):
    optimizer = torch.optim.Adam(
        model.parameters(), lr=CFG.learning_rate, weight_decay=CFG.weight_decay
    )
    criterion = nn.BCEWithLogitsLoss(reduction="none")
    best_ndcg = -np.inf
    best_state = None
    stale_epochs = 0
    history = []

    for epoch in range(1, CFG.max_epochs + 1):
        started = time.time()
        model.train()
        total_loss = 0.0
        total_targets = 0

        for inputs, positives, negatives in train_loader:
            inputs = inputs.to(DEVICE, non_blocking=True)
            positives = positives.to(DEVICE, non_blocking=True)
            negatives = negatives.to(DEVICE, non_blocking=True)
            mask = positives.ne(0)

            optimizer.zero_grad(set_to_none=True)
            features = model(inputs)
            pos_logits = (features * model.item_embedding(positives)).sum(dim=-1)
            neg_logits = (features * model.item_embedding(negatives)).sum(dim=-1)
            losses = criterion(pos_logits, torch.ones_like(pos_logits))
            losses += criterion(neg_logits, torch.zeros_like(neg_logits))
            loss = losses[mask].mean()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            optimizer.step()

            n_targets = int(mask.sum())
            total_loss += float(loss) * n_targets
            total_targets += n_targets

        val_metrics = evaluate_sasrec(
            model, val_contexts, val_targets, val_negatives,
            batch_size=CFG.eval_batch_size, k=CFG.top_k,
        )
        row = {
            "epoch": epoch,
            "train_loss": total_loss / total_targets,
            **val_metrics,
            "seconds": time.time() - started,
        }
        history.append(row)
        print(row)

        current = val_metrics[f"NDCG@{CFG.top_k}"]
        if current > best_ndcg + CFG.min_delta:
            best_ndcg = current
            best_state = copy.deepcopy(model.state_dict())
            stale_epochs = 0
        else:
            stale_epochs += 1
            if stale_epochs >= CFG.patience:
                print(f"Early stopping after epoch {epoch}; best validation NDCG@{CFG.top_k}={best_ndcg:.6f}")
                break

    if best_state is None:
        raise RuntimeError("Training produced no checkpoint")
    model.load_state_dict(best_state)
    return pd.DataFrame(history), best_state


# Training is run in the validation-only tuning section below.
# Keeping this helper separate prevents an untuned SASRec run from using the test set.

## 10. Final evaluation and comparison

Run the test evaluation only after architecture and training choices have been fixed from validation performance. Report the candidate-set protocol alongside every metric table; otherwise results are easily mistaken for full-catalogue ranking.

In [13]:
# The following tuning section selects all neural configurations from validation NDCG@10.
# Test metrics are calculated exactly once for each validation-selected architecture.

## 10. Validation-only neural tuning and GRU4Rec comparison

SASRec settings and GRU4Rec settings are trained on the same prefix-to-next-item task. Each trial is selected only by validation NDCG@10. After choosing the best configuration within each architecture, the two selected models are evaluated once on the untouched test split. GRU4Rec uses right padding and packed GRU sequences so padding cannot update its hidden state.

In [9]:
class GRU4RecTrainDataset(SASRecTrainDataset):
    """Prefix-to-next-item data with right padding for packed GRU processing."""
    def __getitem__(self, index: int):
        user = self.users[index]
        seq = self.sequences[user]
        raw_inputs = seq[:-1][-self.max_len:]
        raw_positives = seq[1:][-self.max_len:]
        n = len(raw_inputs)
        inputs = np.zeros(self.max_len, dtype=np.int64)
        positives = np.zeros(self.max_len, dtype=np.int64)
        negatives = np.zeros(self.max_len, dtype=np.int64)
        inputs[:n] = np.asarray(raw_inputs) + 1
        positives[:n] = np.asarray(raw_positives) + 1
        negatives[:n] = np.asarray([self._negative(self.seen[user]) for _ in range(n)]) + 1
        return torch.from_numpy(inputs), torch.from_numpy(positives), torch.from_numpy(negatives)


class MixedNegativeGRU4RecTrainDataset(GRU4RecTrainDataset):
    """Two negatives per target: one uniform and one popularity-weighted hard negative."""
    def __init__(self, sequences, num_items, max_len, num_negatives: int = 2):
        super().__init__(sequences, num_items, max_len)
        if num_negatives != 2:
            raise ValueError("This controlled experiment uses exactly two negatives")
        self.num_negatives = num_negatives
        weights = np.power(popularity.astype(np.float64) + 1.0, 0.75)
        popularity_probabilities = weights / weights.sum()
        # Sampling from this fixed weighted pool is much faster than invoking
        # np.random.choice(..., p=...) once for every sequence position.
        rng = np.random.default_rng(CFG.seed)
        self.popularity_pool = rng.choice(self.num_items, size=250_000, replace=True, p=popularity_probabilities)

    def _popular_negative(self, seen: set) -> int:
        item = int(self.popularity_pool[np.random.randint(len(self.popularity_pool))])
        while item in seen:
            item = int(self.popularity_pool[np.random.randint(len(self.popularity_pool))])
        return item

    def __getitem__(self, index: int):
        user = self.users[index]
        seq = self.sequences[user]
        raw_inputs, raw_positives = seq[:-1][-self.max_len:], seq[1:][-self.max_len:]
        n = len(raw_inputs)
        inputs = np.zeros(self.max_len, dtype=np.int64)
        positives = np.zeros(self.max_len, dtype=np.int64)
        negatives = np.zeros((self.max_len, self.num_negatives), dtype=np.int64)
        inputs[:n], positives[:n] = np.asarray(raw_inputs) + 1, np.asarray(raw_positives) + 1
        negatives[:n, 0] = np.asarray([self._negative(self.seen[user]) for _ in range(n)]) + 1
        negatives[:n, 1] = np.asarray([self._popular_negative(self.seen[user]) for _ in range(n)]) + 1
        return torch.from_numpy(inputs), torch.from_numpy(positives), torch.from_numpy(negatives)


class GRU4Rec(nn.Module):
    def __init__(self, num_items: int, max_len: int, hidden_dim: int = 64, num_layers: int = 1, dropout: float = 0.1):
        super().__init__()
        self.max_len = max_len
        self.hidden_dim = hidden_dim
        self.item_embedding = nn.Embedding(num_items + 1, hidden_dim, padding_idx=0)
        self.gru = nn.GRU(hidden_dim, hidden_dim, num_layers=num_layers, batch_first=True, dropout=dropout if num_layers > 1 else 0.0)
        self.dropout = nn.Dropout(dropout)
        self.apply(self._init_weights)
        with torch.no_grad():
            self.item_embedding.weight[0].zero_()

    @staticmethod
    def _init_weights(module):
        if isinstance(module, (nn.Linear, nn.Embedding)):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)
        elif isinstance(module, nn.GRU):
            for name, parameter in module.named_parameters():
                if "weight" in name:
                    nn.init.xavier_uniform_(parameter)
                else:
                    nn.init.zeros_(parameter)

    def forward(self, item_ids: torch.Tensor) -> torch.Tensor:
        lengths = item_ids.ne(0).sum(dim=1).clamp_min(1).cpu()
        embedded = self.dropout(self.item_embedding(item_ids))
        packed = nn.utils.rnn.pack_padded_sequence(embedded, lengths, batch_first=True, enforce_sorted=False)
        packed_outputs, _ = self.gru(packed)
        outputs, _ = nn.utils.rnn.pad_packed_sequence(packed_outputs, batch_first=True, total_length=self.max_len)
        return self.dropout(outputs)

    def score_candidates(self, item_ids: torch.Tensor, candidate_ids: torch.Tensor) -> torch.Tensor:
        features = self(item_ids)
        final_positions = item_ids.ne(0).sum(dim=1).clamp_min(1).sub(1)
        context_features = features[torch.arange(item_ids.size(0), device=item_ids.device), final_positions]
        return torch.einsum("bd,bcd->bc", context_features, self.item_embedding(candidate_ids))


def right_pad_context(context: Sequence[int], max_len: int) -> np.ndarray:
    context = list(context)[-max_len:]
    result = np.zeros(max_len, dtype=np.int64)
    if context:
        result[:len(context)] = np.asarray(context, dtype=np.int64) + 1
    return result


@torch.no_grad()
def evaluate_neural(model, contexts, targets, negatives, max_len: int, pad_context, batch_size: int = 512, k: int = 10):
    model.eval()
    ranks = []
    users = sorted(targets)
    for start in range(0, len(users), batch_size):
        batch_users = users[start:start + batch_size]
        inputs = np.stack([pad_context(contexts[user], max_len) for user in batch_users])
        candidates = np.asarray([[targets[user], *negatives[user]] for user in batch_users], dtype=np.int64)
        scores = model.score_candidates(torch.as_tensor(inputs, device=DEVICE), torch.as_tensor(candidates + 1, device=DEVICE)).cpu().numpy()
        ranks.extend(rank_from_scores(user, candidates[row], scores[row], CFG.seed) for row, user in enumerate(batch_users))
    return summarise_ranks(ranks, k)

In [15]:
def make_train_loader(dataset_cls, max_len: int, **dataset_kwargs):
    dataset = dataset_cls(train_sequences, NUM_ITEMS, max_len, **dataset_kwargs)
    dataset.seen = {user: set(sequence).union(held_out_positives[user]) for user, sequence in train_sequences.items()}
    return DataLoader(dataset, batch_size=CFG.batch_size, shuffle=True, num_workers=CFG.num_workers, pin_memory=torch.cuda.is_available())


def train_neural(model, loader, max_len: int, pad_context, learning_rate: float, weight_decay: float, max_epochs: int, patience: int, label: str, loss_name: str = "bce"):
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
    criterion = nn.BCEWithLogitsLoss(reduction="none")
    best_ndcg, best_state, stale_epochs = -np.inf, None, 0
    history = []
    for epoch in range(1, max_epochs + 1):
        started, total_loss, total_targets = time.time(), 0.0, 0
        model.train()
        for inputs, positives, negatives in loader:
            inputs, positives, negatives = (tensor.to(DEVICE, non_blocking=True) for tensor in (inputs, positives, negatives))
            mask = positives.ne(0)
            optimizer.zero_grad(set_to_none=True)
            features = model(inputs)
            pos_logits = (features * model.item_embedding(positives)).sum(dim=-1)
            neg_embeddings = model.item_embedding(negatives)
            neg_logits = (features.unsqueeze(-2) * neg_embeddings).sum(dim=-1) if negatives.ndim == 3 else (features * neg_embeddings).sum(dim=-1)
            if loss_name == "bpr":
                if neg_logits.ndim == 2:
                    neg_logits = neg_logits.unsqueeze(-1)
                loss = torch.nn.functional.softplus(neg_logits - pos_logits.unsqueeze(-1)).mean(dim=-1)[mask].mean()
            elif loss_name == "bce":
                negative_loss = criterion(neg_logits, torch.zeros_like(neg_logits))
                if negative_loss.ndim == 3:
                    negative_loss = negative_loss.mean(dim=-1)
                loss = (criterion(pos_logits, torch.ones_like(pos_logits)) + negative_loss)[mask].mean()
            else:
                raise ValueError(f"Unknown loss_name={loss_name!r}")
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            optimizer.step()
            n_targets = int(mask.sum())
            total_loss += loss.detach().item() * n_targets
            total_targets += n_targets
        val_metrics = evaluate_neural(model, val_contexts, val_targets, val_negatives, max_len, pad_context, CFG.eval_batch_size, CFG.top_k)
        row = {"model": label, "epoch": epoch, "train_loss": total_loss / total_targets, **val_metrics, "seconds": time.time() - started}
        history.append(row)
        print(row)
        current = val_metrics[f"NDCG@{CFG.top_k}"]
        if current > best_ndcg + CFG.min_delta:
            best_ndcg, best_state, stale_epochs = current, copy.deepcopy(model.state_dict()), 0
        else:
            stale_epochs += 1
            if stale_epochs >= patience:
                print(f"{label}: early stopping at epoch {epoch}; best validation NDCG@{CFG.top_k}={best_ndcg:.6f}")
                break
    model.load_state_dict(best_state)
    return pd.DataFrame(history), {name: value.detach().cpu().clone() for name, value in best_state.items()}


SASREC_TRIALS = [
    {"name": "SASRec-short-20", "max_len": 20, "hidden_dim": 64, "num_blocks": 2, "num_heads": 2, "dropout": 0.10, "learning_rate": 1e-3},
]
GRU4REC_TRIALS = [
    {"name": "GRU4Rec-short-10", "max_len": 10, "hidden_dim": 64, "num_layers": 1, "dropout": 0.10, "learning_rate": 1e-3},
    {"name": "GRU4Rec-short-20", "max_len": 20, "hidden_dim": 64, "num_layers": 1, "dropout": 0.10, "learning_rate": 1e-3},
    {"name": "GRU4Rec-short-20-low-lr", "max_len": 20, "hidden_dim": 64, "num_layers": 1, "dropout": 0.10, "learning_rate": 5e-4},
    {"name": "GRU4Rec-short-20-mixedneg-bpr", "max_len": 20, "hidden_dim": 64, "num_layers": 1, "dropout": 0.10, "learning_rate": 1e-3, "dataset_cls": MixedNegativeGRU4RecTrainDataset, "loss_name": "bpr", "num_negatives": 2, "max_epochs": 60},
]
TUNING_EPOCHS, TUNING_PATIENCE, TUNING_WEIGHT_DECAY = 100, 10, 1e-5
SEED_STABILITY_SEEDS = (2026, 2027, 2028)

In [16]:
def run_sasrec_trial(spec):
    seed_everything(CFG.seed)
    loader = make_train_loader(SASRecTrainDataset, spec["max_len"])
    model = SASRec(NUM_ITEMS, spec["max_len"], spec["hidden_dim"], spec["num_blocks"], spec["num_heads"], spec["dropout"]).to(DEVICE)
    history, state = train_neural(model, loader, spec["max_len"], left_pad_context, spec["learning_rate"], TUNING_WEIGHT_DECAY, TUNING_EPOCHS, TUNING_PATIENCE, spec["name"])
    result = {**spec, "architecture": "SASRec", "history": history, "state": state, "parameters": sum(parameter.numel() for parameter in model.parameters())}
    result["validation"] = history.loc[history[f"NDCG@{CFG.top_k}"].idxmax(), [f"Hit@{CFG.top_k}", f"Recall@{CFG.top_k}", f"Precision@{CFG.top_k}", f"CandidateAccuracy@{CFG.top_k}", f"NDCG@{CFG.top_k}", "MRR", "epoch"]].to_dict()
    del model
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return result


def run_gru4rec_trial(spec, seed: int = CFG.seed):
    seed_everything(seed)
    dataset_cls = spec.get("dataset_cls", GRU4RecTrainDataset)
    loader = make_train_loader(dataset_cls, spec["max_len"], **({"num_negatives": spec["num_negatives"]} if "num_negatives" in spec else {}))
    model = GRU4Rec(NUM_ITEMS, spec["max_len"], spec["hidden_dim"], spec["num_layers"], spec["dropout"]).to(DEVICE)
    history, state = train_neural(model, loader, spec["max_len"], right_pad_context, spec["learning_rate"], TUNING_WEIGHT_DECAY, spec.get("max_epochs", TUNING_EPOCHS), TUNING_PATIENCE, spec["name"], spec.get("loss_name", "bce"))
    result = {**spec, "architecture": "GRU4Rec", "seed": seed, "history": history, "state": state, "parameters": sum(parameter.numel() for parameter in model.parameters())}
    result["validation"] = history.loc[history[f"NDCG@{CFG.top_k}"].idxmax(), [f"Hit@{CFG.top_k}", f"Recall@{CFG.top_k}", f"Precision@{CFG.top_k}", f"CandidateAccuracy@{CFG.top_k}", f"NDCG@{CFG.top_k}", "MRR", "epoch"]].to_dict()
    del model
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return result


sasrec_trials = [run_sasrec_trial(spec) for spec in SASREC_TRIALS]
gru4rec_trials = [run_gru4rec_trial(spec) for spec in GRU4REC_TRIALS]
all_trials = sasrec_trials + gru4rec_trials
tuning_validation_df = pd.DataFrame([{key: (value.__name__ if key == "dataset_cls" else value) for key, value in trial.items() if key not in {"history", "state", "validation"}} | trial["validation"] for trial in all_trials])
tuning_validation_df.sort_values(f"NDCG@{CFG.top_k}", ascending=False)

C:\Users\al\AppData\Local\Temp\ipykernel_45112\1547733667.py:26: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.encoder = nn.TransformerEncoder(layer, num_layers=num_blocks)

{'model': 'SASRec-short-20', 'epoch': 1, 'train_loss': 1.2759256489489401, 'Hit@10': 0.12595002081181494, 'Recall@10': 0.12595002081181494, 'NDCG@10': 0.061854932657149614, 'MRR': 0.06517440891011472, 'users': 64867, 'seconds': 6.982460260391235}
{'model': 'SASRec-short-20', 'epoch': 2, 'train_loss': 1.0625843244936604, 'Hit@10': 0.13510721938736184, 'Recall@10': 0.13510721938736184, 'NDCG@10': 0.06758319701412561, 'MRR': 0.06989792306233811, 'users': 64867, 'seconds': 5.86835789680481}
{'model': 'SASRec-short-20', 'epoch': 3, 'train_loss': 0.8935595211696183, 'Hit@10': 0.14303112522546133, 'Recall@10': 0.14303112522546133, 'NDCG@10': 0.0732296176284385, 'MRR': 0.07461675251344778, 'users': 64867, 'seconds': 5.92006778717041}
{'model': 'SASRec-short-20', 'epoch': 4, 'train_loss': 0.7449604687108645, 'Hit@10': 0.14711640741825582, 'Recall@10': 0.14711640741825582, 'NDCG@10': 0.07661439817820759, 'MRR': 0.07760387272599634, 'users': 64867, 'seconds': 5.823467254638672}
{'model': 'SASRec-short-20', 'epoch': 5, 'train_loss': 0.6135947057296781, 'Hit@10': 0.15027672005796475, 'Recall@10': 0.15027672005796475, 'NDCG@10': 0.07971303312077396, 'MRR': 0.08058334001209953, 'users': 64867, 'seconds': 5.76211404800415}
{'model': 'SASRec-short-20', 'epoch': 6, 'train_loss': 0.5038015497334972, 'Hit@10': 0.15372993972281745, 'Recall@10': 0.15372993972281745, 'NDCG@10': 0.08264489946124891, 'MRR': 0.08324975472970886, 'users': 64867, 'seconds': 5.774210453033447}
{'model': 'SASRec-short-20', 'epoch': 7, 'train_loss': 0.4187102620559344, 'Hit@10': 0.1560731959239675, 'Recall@10': 0.1560731959239675, 'NDCG@10': 0.08460476003739566, 'MRR': 0.08502238858394777, 'users': 64867, 'seconds': 5.833637714385986}
{'model': 'SASRec-short-20', 'epoch': 8, 'train_loss': 0.35271199312059043, 'Hit@10': 0.15800021582622906, 'Recall@10': 0.15800021582622906, 'NDCG@10': 0.08686269109945612, 'MRR': 0.08735168903359052, 'users': 64867, 'seconds': 5.870434284210205}
{'model': 'SASRec-short-20', 'epoch': 9, 'train_loss': 0.303366072878625, 'Hit@10': 0.1599272357284906, 'Recall@10': 0.1599272357284906, 'NDCG@10': 0.088536032512635, 'MRR': 0.0888717583882724, 'users': 64867, 'seconds': 5.863851547241211}
{'model': 'SASRec-short-20', 'epoch': 10, 'train_loss': 0.2662697484876277, 'Hit@10': 0.16142260317264556, 'Recall@10': 0.16142260317264556, 'NDCG@10': 0.09007714682041149, 'MRR': 0.09038505133369029, 'users': 64867, 'seconds': 6.229310750961304}
{'model': 'SASRec-short-20', 'epoch': 11, 'train_loss': 0.23805621183917208, 'Hit@10': 0.16202383338215118, 'Recall@10': 0.16202383338215118, 'NDCG@10': 0.09058929240346818, 'MRR': 0.090853795759235, 'users': 64867, 'seconds': 5.9920947551727295}
{'model': 'SASRec-short-20', 'epoch': 12, 'train_loss': 0.2139383975519254, 'Hit@10': 0.16328795843803476, 'Recall@10': 0.16328795843803476, 'NDCG@10': 0.09160954886364912, 'MRR': 0.0917320046290733, 'users': 64867, 'seconds': 6.240828037261963}
{'model': 'SASRec-short-20', 'epoch': 13, 'train_loss': 0.1964751213931959, 'Hit@10': 0.1645674996531364, 'Recall@10': 0.1645674996531364, 'NDCG@10': 0.09245363979254467, 'MRR': 0.09239706136937886, 'users': 64867, 'seconds': 6.0082924365997314}
{'model': 'SASRec-short-20', 'epoch': 14, 'train_loss': 0.18252837329786775, 'Hit@10': 0.16404335023972128, 'Recall@10': 0.16404335023972128, 'NDCG@10': 0.09243942672586082, 'MRR': 0.09256282550374692, 'users': 64867, 'seconds': 5.781706094741821}
{'model': 'SASRec-short-20', 'epoch': 15, 'train_loss': 0.1706532746931421, 'Hit@10': 0.16453666733470024, 'Recall@10': 0.16453666733470024, 'NDCG@10': 0.09266876300849623, 'MRR': 0.09269814894475704, 'users': 64867, 'seconds': 6.00433611869812}
{'model': 'SASRec-short-20', 'epoch': 16, 'train_loss': 0.15773641888192122, 'Hit@10': 0.16449041885704596, 'Recall@10': 0.16449041885704596, 'NDCG@10': 0.09335379171775679, 'MRR': 0.09362323976812219, 'users': 64867, 'seconds': 5.917677640914917}
{'model': 'SASRec-short-20', 'epoch': 17, 'train_loss': 0.15223484232823015, 'Hit@10': 0.16573912775371144, 'Recall@10': 0.16573912775371144, 'NDCG@10': 0.09402244517457539, 'MRR': 0.09407557244156864, 'users': 64867, 'seconds': 6.202955961227417}
{'model': 'SASRec-short-20', 'epoch': 18, 'train_loss': 0.14389553912920597, 'Hit@10': 0.16597037014198282, 'Recall@10': 0.16597037014198282, 'NDCG@10': 0.09436269991666435, 'MRR': 0.09443774235673102, 'users': 64867, 'seconds': 5.805354595184326}
{'model': 'SASRec-short-20', 'epoch': 19, 'train_loss': 0.13817614841654394, 'Hit@10': 0.1656003823207486, 'Recall@10': 0.1656003823207486, 'NDCG@10': 0.093985109007107, 'MRR': 0.09407107114073437, 'users': 64867, 'seconds': 5.761977434158325}
{'model': 'SASRec-short-20', 'epoch': 20, 'train_loss': 0.13266806237741258, 'Hit@10': 0.16629410948556278, 'Recall@10': 0.16629410948556278, 'NDCG@10': 0.09509308958461934, 'MRR': 0.09530555184070424, 'users': 64867, 'seconds': 6.057507753372192}
{'model': 'SASRec-short-20', 'epoch': 21, 'train_loss': 0.12771867867080125, 'Hit@10': 0.16737324063082923, 'Recall@10': 0.16737324063082923, 'NDCG@10': 0.09551798108664859, 'MRR': 0.09548593037713476, 'users': 64867, 'seconds': 5.882350444793701}
{'model': 'SASRec-short-20', 'epoch': 22, 'train_loss': 0.12394239817710072, 'Hit@10': 0.16728074367552068, 'Recall@10': 0.16728074367552068, 'NDCG@10': 0.09546114660034495, 'MRR': 0.09540748892117192, 'users': 64867, 'seconds': 6.063281297683716}
{'model': 'SASRec-short-20', 'epoch': 23, 'train_loss': 0.11946482082770066, 'Hit@10': 0.16700325280959502, 'Recall@10': 0.16700325280959502, 'NDCG@10': 0.09514646547186312, 'MRR': 0.09511359743126088, 'users': 64867, 'seconds': 6.417402744293213}
{'model': 'SASRec-short-20', 'epoch': 24, 'train_loss': 0.11727059969415965, 'Hit@10': 0.1672499113570845, 'Recall@10': 0.1672499113570845, 'NDCG@10': 0.09569328405436406, 'MRR': 0.09572502459231783, 'users': 64867, 'seconds': 5.771224498748779}
{'model': 'SASRec-short-20', 'epoch': 25, 'train_loss': 0.11330842564118161, 'Hit@10': 0.1672344951978664, 'Recall@10': 0.1672344951978664, 'NDCG@10': 0.09561981266127972, 'MRR': 0.0956634433600432, 'users': 64867, 'seconds': 5.8785080909729}
{'model': 'SASRec-short-20', 'epoch': 26, 'train_loss': 0.11159169849696306, 'Hit@10': 0.16783572540737202, 'Recall@10': 0.16783572540737202, 'NDCG@10': 0.09605956874000945, 'MRR': 0.09603565582061147, 'users': 64867, 'seconds': 6.578303337097168}
{'model': 'SASRec-short-20', 'epoch': 27, 'train_loss': 0.10949985351166286, 'Hit@10': 0.1678048930889358, 'Recall@10': 0.1678048930889358, 'NDCG@10': 0.09608619111926647, 'MRR': 0.0960666076261686, 'users': 64867, 'seconds': 7.162127494812012}
{'model': 'SASRec-short-20', 'epoch': 28, 'train_loss': 0.10783534609377488, 'Hit@10': 0.1678665577258082, 'Recall@10': 0.1678665577258082, 'NDCG@10': 0.09618943973989558, 'MRR': 0.09617689770861737, 'users': 64867, 'seconds': 7.089677095413208}
{'model': 'SASRec-short-20', 'epoch': 29, 'train_loss': 0.10478184775815919, 'Hit@10': 0.1676815638151911, 'Recall@10': 0.1676815638151911, 'NDCG@10': 0.09643665740942438, 'MRR': 0.09657555171144595, 'users': 64867, 'seconds': 6.837802410125732}
{'model': 'SASRec-short-20', 'epoch': 30, 'train_loss': 0.10237500909119475, 'Hit@10': 0.16791280620346247, 'Recall@10': 0.16791280620346247, 'NDCG@10': 0.09663611904838747, 'MRR': 0.09677205401023928, 'users': 64867, 'seconds': 6.8063600063323975}
{'model': 'SASRec-short-20', 'epoch': 31, 'train_loss': 0.10255806687879308, 'Hit@10': 0.16840612329844143, 'Recall@10': 0.16840612329844143, 'NDCG@10': 0.09669564628283375, 'MRR': 0.09668142259161612, 'users': 64867, 'seconds': 6.7811384201049805}
{'model': 'SASRec-short-20', 'epoch': 32, 'train_loss': 0.09793029953518162, 'Hit@10': 0.16848320409453188, 'Recall@10': 0.16848320409453188, 'NDCG@10': 0.09683334411705245, 'MRR': 0.0968331637121548, 'users': 64867, 'seconds': 7.1230974197387695}
{'model': 'SASRec-short-20', 'epoch': 33, 'train_loss': 0.09880128661835394, 'Hit@10': 0.16829821018391478, 'Recall@10': 0.16829821018391478, 'NDCG@10': 0.09688657223762052, 'MRR': 0.09696296493119833, 'users': 64867, 'seconds': 7.053752183914185}
{'model': 'SASRec-short-20', 'epoch': 34, 'train_loss': 0.09781951060749522, 'Hit@10': 0.16783572540737202, 'Recall@10': 0.16783572540737202, 'NDCG@10': 0.09674123614749454, 'MRR': 0.09694385478992004, 'users': 64867, 'seconds': 7.4149487018585205}
{'model': 'SASRec-short-20', 'epoch': 35, 'train_loss': 0.0956277658750522, 'Hit@10': 0.16803613547720722, 'Recall@10': 0.16803613547720722, 'NDCG@10': 0.09680690494787231, 'MRR': 0.09695594323751243, 'users': 64867, 'seconds': 7.1155219078063965}
{'model': 'SASRec-short-20', 'epoch': 36, 'train_loss': 0.09553946413194904, 'Hit@10': 0.16774322845206346, 'Recall@10': 0.16774322845206346, 'NDCG@10': 0.09667664848333694, 'MRR': 0.09687231340588881, 'users': 64867, 'seconds': 7.042805194854736}
{'model': 'SASRec-short-20', 'epoch': 37, 'train_loss': 0.09439438475497892, 'Hit@10': 0.16860653336827663, 'Recall@10': 0.16860653336827663, 'NDCG@10': 0.09723646435041707, 'MRR': 0.09728922054218958, 'users': 64867, 'seconds': 6.901226997375488}
{'model': 'SASRec-short-20', 'epoch': 38, 'train_loss': 0.09288079277192926, 'Hit@10': 0.1688223595973299, 'Recall@10': 0.1688223595973299, 'NDCG@10': 0.09741164293509909, 'MRR': 0.09744441786822268, 'users': 64867, 'seconds': 6.93904447555542}
{'model': 'SASRec-short-20', 'epoch': 39, 'train_loss': 0.09102131083122217, 'Hit@10': 0.16842153945765953, 'Recall@10': 0.16842153945765953, 'NDCG@10': 0.09703364839232179, 'MRR': 0.09711567150023633, 'users': 64867, 'seconds': 6.991576194763184}
{'model': 'SASRec-short-20', 'epoch': 40, 'train_loss': 0.08963259126667271, 'Hit@10': 0.16866819800514898, 'Recall@10': 0.16866819800514898, 'NDCG@10': 0.09730915795564413, 'MRR': 0.09736720802263495, 'users': 64867, 'seconds': 6.919946670532227}
{'model': 'SASRec-short-20', 'epoch': 41, 'train_loss': 0.08946883308104553, 'Hit@10': 0.1688223595973299, 'Recall@10': 0.1688223595973299, 'NDCG@10': 0.09711131606790865, 'MRR': 0.09704474833028723, 'users': 64867, 'seconds': 7.012735843658447}
{'model': 'SASRec-short-20', 'epoch': 42, 'train_loss': 0.08880890783305617, 'Hit@10': 0.16996315537946877, 'Recall@10': 0.16996315537946877, 'NDCG@10': 0.09812536402386222, 'MRR': 0.09797918576273701, 'users': 64867, 'seconds': 7.131659030914307}
{'model': 'SASRec-short-20', 'epoch': 43, 'train_loss': 0.08919657627349135, 'Hit@10': 0.16919234741856415, 'Recall@10': 0.16919234741856415, 'NDCG@10': 0.09783163614613595, 'MRR': 0.0978660190837126, 'users': 64867, 'seconds': 7.032508611679077}
{'model': 'SASRec-short-20', 'epoch': 44, 'train_loss': 0.08735109227659998, 'Hit@10': 0.16914609894090987, 'Recall@10': 0.16914609894090987, 'NDCG@10': 0.09787815210592468, 'MRR': 0.09796623025608546, 'users': 64867, 'seconds': 6.866140127182007}
{'model': 'SASRec-short-20', 'epoch': 45, 'train_loss': 0.08524900581166846, 'Hit@10': 0.16899193734872894, 'Recall@10': 0.16899193734872894, 'NDCG@10': 0.09770352564695449, 'MRR': 0.0977822432395142, 'users': 64867, 'seconds': 7.198282480239868}
{'model': 'SASRec-short-20', 'epoch': 46, 'train_loss': 0.0850863702467239, 'Hit@10': 0.1694544221252717, 'Recall@10': 0.1694544221252717, 'NDCG@10': 0.0977207829656852, 'MRR': 0.09763041146402236, 'users': 64867, 'seconds': 6.860383033752441}
{'model': 'SASRec-short-20', 'epoch': 47, 'train_loss': 0.08444061177943872, 'Hit@10': 0.16982440994650594, 'Recall@10': 0.16982440994650594, 'NDCG@10': 0.09817157079383726, 'MRR': 0.09811390117162305, 'users': 64867, 'seconds': 6.904569149017334}
{'model': 'SASRec-short-20', 'epoch': 48, 'train_loss': 0.08331367137180869, 'Hit@10': 0.16913068278169177, 'Recall@10': 0.16913068278169177, 'NDCG@10': 0.09742932068976466, 'MRR': 0.09735391084248128, 'users': 64867, 'seconds': 6.982126474380493}
{'model': 'SASRec-short-20', 'epoch': 49, 'train_loss': 0.08294500814049335, 'Hit@10': 0.1692540120554365, 'Recall@10': 0.1692540120554365, 'NDCG@10': 0.09786074342348512, 'MRR': 0.09790644292774033, 'users': 64867, 'seconds': 6.904695510864258}
{'model': 'SASRec-short-20', 'epoch': 50, 'train_loss': 0.08093092482314741, 'Hit@10': 0.1694852544437079, 'Recall@10': 0.1694852544437079, 'NDCG@10': 0.09799074362939172, 'MRR': 0.09803138926158364, 'users': 64867, 'seconds': 7.023181915283203}
{'model': 'SASRec-short-20', 'epoch': 51, 'train_loss': 0.08145920411488883, 'Hit@10': 0.169670248354325, 'Recall@10': 0.169670248354325, 'NDCG@10': 0.09786126915120574, 'MRR': 0.09776471237884475, 'users': 64867, 'seconds': 6.8773791790008545}
{'model': 'SASRec-short-20', 'epoch': 52, 'train_loss': 0.08125011234255046, 'Hit@10': 0.1694544221252717, 'Recall@10': 0.1694544221252717, 'NDCG@10': 0.09793402549078425, 'MRR': 0.09796896910689684, 'users': 64867, 'seconds': 7.007178544998169}
{'model': 'SASRec-short-20', 'epoch': 53, 'train_loss': 0.08151921672266631, 'Hit@10': 0.16876069496045756, 'Recall@10': 0.16876069496045756, 'NDCG@10': 0.09779370667186683, 'MRR': 0.09802660283336712, 'users': 64867, 'seconds': 6.798768043518066}
{'model': 'SASRec-short-20', 'epoch': 54, 'train_loss': 0.07914504542295357, 'Hit@10': 0.16916151510012795, 'Recall@10': 0.16916151510012795, 'NDCG@10': 0.09775435447681204, 'MRR': 0.09780822568494174, 'users': 64867, 'seconds': 6.898232698440552}
{'model': 'SASRec-short-20', 'epoch': 55, 'train_loss': 0.07944078098497397, 'Hit@10': 0.16919234741856415, 'Recall@10': 0.16919234741856415, 'NDCG@10': 0.09796065853423347, 'MRR': 0.09806331165775728, 'users': 64867, 'seconds': 6.895035743713379}
{'model': 'SASRec-short-20', 'epoch': 56, 'train_loss': 0.07907654487601996, 'Hit@10': 0.16930026053309077, 'Recall@10': 0.16930026053309077, 'NDCG@10': 0.09786674559535607, 'MRR': 0.09788703082375433, 'users': 64867, 'seconds': 7.426353216171265}
{'model': 'SASRec-short-20', 'epoch': 57, 'train_loss': 0.07776219199625, 'Hit@10': 0.16960858371745263, 'Recall@10': 0.16960858371745263, 'NDCG@10': 0.09793540995426961, 'MRR': 0.09784682412859091, 'users': 64867, 'seconds': 6.918805122375488}
SASRec-short-20: early stopping at epoch 57; best validation NDCG@10=0.098172
{'model': 'GRU4Rec-short-10', 'epoch': 1, 'train_loss': 1.2937142551538254, 'Hit@10': 0.40172969306427, 'Recall@10': 0.40172969306427, 'NDCG@10': 0.2458877003049039, 'MRR': 0.21748005163699244, 'users': 64867, 'seconds': 6.085626840591431}
{'model': 'GRU4Rec-short-10', 'epoch': 2, 'train_loss': 1.148159868281811, 'Hit@10': 0.43097414710099125, 'Recall@10': 0.43097414710099125, 'NDCG@10': 0.26148750598038456, 'MRR': 0.22941011156812097, 'users': 64867, 'seconds': 6.239208936691284}
{'model': 'GRU4Rec-short-10', 'epoch': 3, 'train_loss': 1.0782169600164158, 'Hit@10': 0.457289530886275, 'Recall@10': 0.457289530886275, 'NDCG@10': 0.27760041063381125, 'MRR': 0.24246399375197095, 'users': 64867, 'seconds': 6.070509910583496}
{'model': 'GRU4Rec-short-10', 'epoch': 4, 'train_loss': 1.0188674586059647, 'Hit@10': 0.47890298611004056, 'Recall@10': 0.47890298611004056, 'NDCG@10': 0.29260496881810516, 'MRR': 0.2551863489781739, 'users': 64867, 'seconds': 6.425248146057129}
{'model': 'GRU4Rec-short-10', 'epoch': 5, 'train_loss': 0.9702304712689195, 'Hit@10': 0.4929625233169408, 'Recall@10': 0.4929625233169408, 'NDCG@10': 0.3020167396148688, 'MRR': 0.2628468888402306, 'users': 64867, 'seconds': 6.345075368881226}
{'model': 'GRU4Rec-short-10', 'epoch': 6, 'train_loss': 0.9287564155771257, 'Hit@10': 0.5003622797416252, 'Recall@10': 0.5003622797416252, 'NDCG@10': 0.30939076718597774, 'MRR': 0.2702264266972953, 'users': 64867, 'seconds': 6.326359272003174}
{'model': 'GRU4Rec-short-10', 'epoch': 7, 'train_loss': 0.8946872596548446, 'Hit@10': 0.5092265712920283, 'Recall@10': 0.5092265712920283, 'NDCG@10': 0.31405207491157905, 'MRR': 0.27336442854135745, 'users': 64867, 'seconds': 6.44898247718811}
{'model': 'GRU4Rec-short-10', 'epoch': 8, 'train_loss': 0.862758080418146, 'Hit@10': 0.5168884024234203, 'Recall@10': 0.5168884024234203, 'NDCG@10': 0.3199055597074104, 'MRR': 0.27849366092772937, 'users': 64867, 'seconds': 6.1455254554748535}
{'model': 'GRU4Rec-short-10', 'epoch': 9, 'train_loss': 0.8341634481624386, 'Hit@10': 0.521343672437449, 'Recall@10': 0.521343672437449, 'NDCG@10': 0.32236724190214544, 'MRR': 0.28033656222115894, 'users': 64867, 'seconds': 6.1881914138793945}
{'model': 'GRU4Rec-short-10', 'epoch': 10, 'train_loss': 0.806042693346061, 'Hit@10': 0.5250743829682273, 'Recall@10': 0.5250743829682273, 'NDCG@10': 0.3272132875470872, 'MRR': 0.28550250171261105, 'users': 64867, 'seconds': 6.287359952926636}
{'model': 'GRU4Rec-short-10', 'epoch': 11, 'train_loss': 0.7797873314484478, 'Hit@10': 0.531364175929209, 'Recall@10': 0.531364175929209, 'NDCG@10': 0.330372054076348, 'MRR': 0.28756392660711705, 'users': 64867, 'seconds': 6.3213722705841064}
{'model': 'GRU4Rec-short-10', 'epoch': 12, 'train_loss': 0.7569558329668075, 'Hit@10': 0.5354186258035672, 'Recall@10': 0.5354186258035672, 'NDCG@10': 0.3339038189479434, 'MRR': 0.290737545844249, 'users': 64867, 'seconds': 6.1356940269470215}
{'model': 'GRU4Rec-short-10', 'epoch': 13, 'train_loss': 0.7340899263838081, 'Hit@10': 0.5410455239181711, 'Recall@10': 0.5410455239181711, 'NDCG@10': 0.33790574414868124, 'MRR': 0.2939849855586799, 'users': 64867, 'seconds': 5.993525266647339}
{'model': 'GRU4Rec-short-10', 'epoch': 14, 'train_loss': 0.7139774457625083, 'Hit@10': 0.5448378990858218, 'Recall@10': 0.5448378990858218, 'NDCG@10': 0.3401895789909759, 'MRR': 0.2956447042434871, 'users': 64867, 'seconds': 6.213052034378052}
{'model': 'GRU4Rec-short-10', 'epoch': 15, 'train_loss': 0.6950506549448515, 'Hit@10': 0.5471657391277537, 'Recall@10': 0.5471657391277537, 'NDCG@10': 0.34288017064281895, 'MRR': 0.2983625173224065, 'users': 64867, 'seconds': 6.62946343421936}
{'model': 'GRU4Rec-short-10', 'epoch': 16, 'train_loss': 0.6767844959603498, 'Hit@10': 0.5517597545747452, 'Recall@10': 0.5517597545747452, 'NDCG@10': 0.34584552194425, 'MRR': 0.3006134475329637, 'users': 64867, 'seconds': 6.114998817443848}
{'model': 'GRU4Rec-short-10', 'epoch': 17, 'train_loss': 0.66116291692023, 'Hit@10': 0.5549200672144542, 'Recall@10': 0.5549200672144542, 'NDCG@10': 0.3487585496291537, 'MRR': 0.3032600039210907, 'users': 64867, 'seconds': 6.080570697784424}
{'model': 'GRU4Rec-short-10', 'epoch': 18, 'train_loss': 0.6458684173790701, 'Hit@10': 0.5590824302033391, 'Recall@10': 0.5590824302033391, 'NDCG@10': 0.3510886679121393, 'MRR': 0.30482336413531597, 'users': 64867, 'seconds': 6.180425405502319}
{'model': 'GRU4Rec-short-10', 'epoch': 19, 'train_loss': 0.6305797899997535, 'Hit@10': 0.5594370018653553, 'Recall@10': 0.5594370018653553, 'NDCG@10': 0.3529835711277102, 'MRR': 0.3071867447458686, 'users': 64867, 'seconds': 6.355687618255615}
{'model': 'GRU4Rec-short-10', 'epoch': 20, 'train_loss': 0.6161199904125, 'Hit@10': 0.5609323693095102, 'Recall@10': 0.5609323693095102, 'NDCG@10': 0.3547908964032476, 'MRR': 0.30904454125067343, 'users': 64867, 'seconds': 6.020209074020386}
{'model': 'GRU4Rec-short-10', 'epoch': 21, 'train_loss': 0.6016046090071816, 'Hit@10': 0.5639231041978201, 'Recall@10': 0.5639231041978201, 'NDCG@10': 0.35703726627866955, 'MRR': 0.3110081910057705, 'users': 64867, 'seconds': 6.30201268196106}
{'model': 'GRU4Rec-short-10', 'epoch': 22, 'train_loss': 0.5909325051559787, 'Hit@10': 0.5658655402592998, 'Recall@10': 0.5658655402592998, 'NDCG@10': 0.35832564929621985, 'MRR': 0.3120065517579642, 'users': 64867, 'seconds': 6.238908052444458}
{'model': 'GRU4Rec-short-10', 'epoch': 23, 'train_loss': 0.5782123486410209, 'Hit@10': 0.5682242126196679, 'Recall@10': 0.5682242126196679, 'NDCG@10': 0.3596704384061068, 'MRR': 0.31290803039622356, 'users': 64867, 'seconds': 5.9930260181427}
{'model': 'GRU4Rec-short-10', 'epoch': 24, 'train_loss': 0.5658355013794683, 'Hit@10': 0.570567468820818, 'Recall@10': 0.570567468820818, 'NDCG@10': 0.36313763786424885, 'MRR': 0.31662213865704075, 'users': 64867, 'seconds': 6.11966609954834}

,name,max_len,hidden_dim,num_blocks,num_heads,dropout,learning_rate,architecture,parameters,Hit@10,Recall@10,NDCG@10,MRR,epoch,num_layers,seed
2,GRU4Rec-short-20,20,64,NaN,NaN,0.1,0.0010,GRU4Rec,5229632,0.677725,0.677725,0.455477,0.400238,99,1.0,2026.0
3,GRU4Rec-short-20-low-lr,20,64,NaN,NaN,0.1,0.0005,GRU4Rec,5229632,0.641497,0.641497,0.421944,0.369237,100,1.0,2026.0
1,GRU4Rec-short-10,10,64,NaN,NaN,0.1,0.0010,GRU4Rec,5229632,0.624169,0.624169,0.412942,0.362483,99,1.0,2026.0
0,SASRec-short-20,20,64,2.0,2.0,0.1,0.0010,SASRec,5306048,0.169824,0.169824,0.098172,0.098114,47,NaN,NaN

In [17]:
# Repeat only the validation-selected GRU configuration across seeds.
# These runs quantify stability; they do not use the test set.
best_gru_for_stability = max(gru4rec_trials, key=lambda trial: trial["validation"][f"NDCG@{CFG.top_k}"])
seed_stability_trials = [best_gru_for_stability] + [
    run_gru4rec_trial(best_gru_for_stability, seed=seed)
    for seed in SEED_STABILITY_SEEDS if seed != best_gru_for_stability["seed"]
]
seed_stability_df = pd.DataFrame([{
    "seed": trial["seed"], "epoch": trial["validation"]["epoch"],
    f"NDCG@{CFG.top_k}": trial["validation"][f"NDCG@{CFG.top_k}"],
    f"Recall@{CFG.top_k}": trial["validation"][f"Recall@{CFG.top_k}"],
    f"Precision@{CFG.top_k}": trial["validation"][f"Precision@{CFG.top_k}"],
    f"CandidateAccuracy@{CFG.top_k}": trial["validation"][f"CandidateAccuracy@{CFG.top_k}"],
    "MRR": trial["validation"]["MRR"],
} for trial in seed_stability_trials])
seed_stability_summary = seed_stability_df.drop(columns=["seed", "epoch"]).agg(["mean", "std"])
display(seed_stability_df)
display(seed_stability_summary)

{'model': 'GRU4Rec-short-20', 'epoch': 1, 'train_loss': 1.2995715444381686, 'Hit@10': 0.4059537206900273, 'Recall@10': 0.4059537206900273, 'NDCG@10': 0.24891042511563582, 'MRR': 0.220034742594839, 'users': 64867, 'seconds': 7.454541921615601}
{'model': 'GRU4Rec-short-20', 'epoch': 2, 'train_loss': 1.1587812205395296, 'Hit@10': 0.43943761851172397, 'Recall@10': 0.43943761851172397, 'NDCG@10': 0.26640495512171253, 'MRR': 0.23318914239233315, 'users': 64867, 'seconds': 7.296975612640381}
{'model': 'GRU4Rec-short-20', 'epoch': 3, 'train_loss': 1.0856845564950595, 'Hit@10': 0.46934496739482323, 'Recall@10': 0.46934496739482323, 'NDCG@10': 0.28518727398099725, 'MRR': 0.2486897275773254, 'users': 64867, 'seconds': 7.227041721343994}
{'model': 'GRU4Rec-short-20', 'epoch': 4, 'train_loss': 1.0242033883743837, 'Hit@10': 0.49007970154315755, 'Recall@10': 0.49007970154315755, 'NDCG@10': 0.300296738232478, 'MRR': 0.2618661372639495, 'users': 64867, 'seconds': 7.415994882583618}
{'model': 'GRU4Rec-short-20', 'epoch': 5, 'train_loss': 0.9756504092773178, 'Hit@10': 0.5031526045600999, 'Recall@10': 0.5031526045600999, 'NDCG@10': 0.3096188871346485, 'MRR': 0.2698106635404761, 'users': 64867, 'seconds': 7.713443040847778}
{'model': 'GRU4Rec-short-20', 'epoch': 6, 'train_loss': 0.9375003788208959, 'Hit@10': 0.5150847117949034, 'Recall@10': 0.5150847117949034, 'NDCG@10': 0.3168343878559519, 'MRR': 0.27535385785138417, 'users': 64867, 'seconds': 7.225207567214966}
{'model': 'GRU4Rec-short-20', 'epoch': 7, 'train_loss': 0.902673926074572, 'Hit@10': 0.5234402700911095, 'Recall@10': 0.5234402700911095, 'NDCG@10': 0.32318295026051796, 'MRR': 0.2811207302524039, 'users': 64867, 'seconds': 7.321133136749268}
{'model': 'GRU4Rec-short-20', 'epoch': 8, 'train_loss': 0.8713917635163102, 'Hit@10': 0.5340928361108114, 'Recall@10': 0.5340928361108114, 'NDCG@10': 0.33057846472461105, 'MRR': 0.28718734720085465, 'users': 64867, 'seconds': 7.165950775146484}
{'model': 'GRU4Rec-short-20', 'epoch': 9, 'train_loss': 0.8409148861306756, 'Hit@10': 0.5394114110410533, 'Recall@10': 0.5394114110410533, 'NDCG@10': 0.335131249245603, 'MRR': 0.29156746055009647, 'users': 64867, 'seconds': 7.366081476211548}
{'model': 'GRU4Rec-short-20', 'epoch': 10, 'train_loss': 0.8137230149095651, 'Hit@10': 0.5500948093791913, 'Recall@10': 0.5500948093791913, 'NDCG@10': 0.34167587662063087, 'MRR': 0.2963831504145259, 'users': 64867, 'seconds': 7.116274356842041}
{'model': 'GRU4Rec-short-20', 'epoch': 11, 'train_loss': 0.790302779558854, 'Hit@10': 0.5548121540999276, 'Recall@10': 0.5548121540999276, 'NDCG@10': 0.3460493193519765, 'MRR': 0.30060247010340546, 'users': 64867, 'seconds': 7.302900552749634}
{'model': 'GRU4Rec-short-20', 'epoch': 12, 'train_loss': 0.7640265580704542, 'Hit@10': 0.5622581590022662, 'Recall@10': 0.5622581590022662, 'NDCG@10': 0.3508611679276506, 'MRR': 0.3043111600616909, 'users': 64867, 'seconds': 7.336503982543945}
{'model': 'GRU4Rec-short-20', 'epoch': 13, 'train_loss': 0.7444603390756828, 'Hit@10': 0.5689025236252641, 'Recall@10': 0.5689025236252641, 'NDCG@10': 0.3557285237469136, 'MRR': 0.30830289093479946, 'users': 64867, 'seconds': 7.472176790237427}
{'model': 'GRU4Rec-short-20', 'epoch': 14, 'train_loss': 0.7253723064242884, 'Hit@10': 0.5732807128432023, 'Recall@10': 0.5732807128432023, 'NDCG@10': 0.359799710124161, 'MRR': 0.3121794159682796, 'users': 64867, 'seconds': 7.3992063999176025}
{'model': 'GRU4Rec-short-20', 'epoch': 15, 'train_loss': 0.7052970381319361, 'Hit@10': 0.577227249603034, 'Recall@10': 0.577227249603034, 'NDCG@10': 0.362643675747097, 'MRR': 0.31457935412596394, 'users': 64867, 'seconds': 7.500345706939697}
{'model': 'GRU4Rec-short-20', 'epoch': 16, 'train_loss': 0.6886472811049043, 'Hit@10': 0.5807729662231952, 'Recall@10': 0.5807729662231952, 'NDCG@10': 0.36589926808305545, 'MRR': 0.3175897548685533, 'users': 64867, 'seconds': 7.794055223464966}
{'model': 'GRU4Rec-short-20', 'epoch': 17, 'train_loss': 0.6717492288822486, 'Hit@10': 0.5862302865863999, 'Recall@10': 0.5862302865863999, 'NDCG@10': 0.37006694138560836, 'MRR': 0.321198779189542, 'users': 64867, 'seconds': 7.484798192977905}
{'model': 'GRU4Rec-short-20', 'epoch': 18, 'train_loss': 0.6561783330934448, 'Hit@10': 0.5890206114048746, 'Recall@10': 0.5890206114048746, 'NDCG@10': 0.3719601128868983, 'MRR': 0.3226812713969095, 'users': 64867, 'seconds': 7.324065923690796}
{'model': 'GRU4Rec-short-20', 'epoch': 19, 'train_loss': 0.6404330277121526, 'Hit@10': 0.5944316832904251, 'Recall@10': 0.5944316832904251, 'NDCG@10': 0.37615222811174426, 'MRR': 0.3262309327725097, 'users': 64867, 'seconds': 7.400291442871094}
{'model': 'GRU4Rec-short-20', 'epoch': 20, 'train_loss': 0.6275202125107284, 'Hit@10': 0.5967903556507932, 'Recall@10': 0.5967903556507932, 'NDCG@10': 0.38004711240481204, 'MRR': 0.33046775696457353, 'users': 64867, 'seconds': 7.400326490402222}
{'model': 'GRU4Rec-short-20', 'epoch': 21, 'train_loss': 0.6137175586384028, 'Hit@10': 0.6009373024804601, 'Recall@10': 0.6009373024804601, 'NDCG@10': 0.3831149049213189, 'MRR': 0.3331099532428695, 'users': 64867, 'seconds': 7.269974946975708}
{'model': 'GRU4Rec-short-20', 'epoch': 22, 'train_loss': 0.6025246317647315, 'Hit@10': 0.6027101607905406, 'Recall@10': 0.6027101607905406, 'NDCG@10': 0.38469868269958063, 'MRR': 0.3345839396966003, 'users': 64867, 'seconds': 7.391924858093262}
{'model': 'GRU4Rec-short-20', 'epoch': 23, 'train_loss': 0.5924238123851292, 'Hit@10': 0.607766661014075, 'Recall@10': 0.607766661014075, 'NDCG@10': 0.38748730630115635, 'MRR': 0.3362844782145816, 'users': 64867, 'seconds': 7.312721252441406}
{'model': 'GRU4Rec-short-20', 'epoch': 24, 'train_loss': 0.5775539183974308, 'Hit@10': 0.6105261535141135, 'Recall@10': 0.6105261535141135, 'NDCG@10': 0.3900293982210502, 'MRR': 0.3388143375771132, 'users': 64867, 'seconds': 7.12123441696167}
{'model': 'GRU4Rec-short-20', 'epoch': 25, 'train_loss': 0.5688442660086244, 'Hit@10': 0.6134860560839872, 'Recall@10': 0.6134860560839872, 'NDCG@10': 0.3927733753811439, 'MRR': 0.34134357445271757, 'users': 64867, 'seconds': 7.339521169662476}
{'model': 'GRU4Rec-short-20', 'epoch': 26, 'train_loss': 0.5584634699800901, 'Hit@10': 0.6150276720057964, 'Recall@10': 0.6150276720057964, 'NDCG@10': 0.39482302549404436, 'MRR': 0.3434827756883412, 'users': 64867, 'seconds': 7.452908754348755}
{'model': 'GRU4Rec-short-20', 'epoch': 27, 'train_loss': 0.5481047026176807, 'Hit@10': 0.6177254998689626, 'Recall@10': 0.6177254998689626, 'NDCG@10': 0.397036524993041, 'MRR': 0.3454380526284994, 'users': 64867, 'seconds': 7.832128047943115}
{'model': 'GRU4Rec-short-20', 'epoch': 28, 'train_loss': 0.5397696093649567, 'Hit@10': 0.6218878628578476, 'Recall@10': 0.6218878628578476, 'NDCG@10': 0.39950706943417813, 'MRR': 0.34709014172007924, 'users': 64867, 'seconds': 7.345731496810913}
{'model': 'GRU4Rec-short-20', 'epoch': 29, 'train_loss': 0.5308625153613006, 'Hit@10': 0.6232444848690397, 'Recall@10': 0.6232444848690397, 'NDCG@10': 0.4018330093531862, 'MRR': 0.34965582190985856, 'users': 64867, 'seconds': 7.2153401374816895}
{'model': 'GRU4Rec-short-20', 'epoch': 30, 'train_loss': 0.5218797140156488, 'Hit@10': 0.6261427228020411, 'Recall@10': 0.6261427228020411, 'NDCG@10': 0.40459440248826994, 'MRR': 0.35222996457778954, 'users': 64867, 'seconds': 7.327101945877075}
{'model': 'GRU4Rec-short-20', 'epoch': 31, 'train_loss': 0.5122407343480827, 'Hit@10': 0.6272064377880895, 'Recall@10': 0.6272064377880895, 'NDCG@10': 0.4058108256786083, 'MRR': 0.3534832376489097, 'users': 64867, 'seconds': 7.2502031326293945}
{'model': 'GRU4Rec-short-20', 'epoch': 32, 'train_loss': 0.5049603108388503, 'Hit@10': 0.6301817565171813, 'Recall@10': 0.6301817565171813, 'NDCG@10': 0.40726497546271284, 'MRR': 0.3542430827096193, 'users': 64867, 'seconds': 7.3972084522247314}
{'model': 'GRU4Rec-short-20', 'epoch': 33, 'train_loss': 0.49901463747113006, 'Hit@10': 0.6324170996038047, 'Recall@10': 0.6324170996038047, 'NDCG@10': 0.40923693815044043, 'MRR': 0.3560023188373627, 'users': 64867, 'seconds': 7.30564022064209}
{'model': 'GRU4Rec-short-20', 'epoch': 34, 'train_loss': 0.4919383973475957, 'Hit@10': 0.6326637581512942, 'Recall@10': 0.6326637581512942, 'NDCG@10': 0.41105356470828297, 'MRR': 0.3584077403695181, 'users': 64867, 'seconds': 7.373009204864502}
{'model': 'GRU4Rec-short-20', 'epoch': 35, 'train_loss': 0.4835808123028186, 'Hit@10': 0.6361786424530192, 'Recall@10': 0.6361786424530192, 'NDCG@10': 0.4137828476091522, 'MRR': 0.36065343565574953, 'users': 64867, 'seconds': 7.448502063751221}
{'model': 'GRU4Rec-short-20', 'epoch': 36, 'train_loss': 0.4782279021875673, 'Hit@10': 0.63730402207594, 'Recall@10': 0.63730402207594, 'NDCG@10': 0.41449770810509073, 'MRR': 0.36119749874031576, 'users': 64867, 'seconds': 7.643137216567993}
{'model': 'GRU4Rec-short-20', 'epoch': 37, 'train_loss': 0.4717707947445932, 'Hit@10': 0.6399401853022338, 'Recall@10': 0.6399401853022338, 'NDCG@10': 0.41645845259606623, 'MRR': 0.3628821998805623, 'users': 64867, 'seconds': 7.537777900695801}
{'model': 'GRU4Rec-short-20', 'epoch': 38, 'train_loss': 0.46475468694309535, 'Hit@10': 0.6419288698413678, 'Recall@10': 0.6419288698413678, 'NDCG@10': 0.4181774805427801, 'MRR': 0.3644298470050645, 'users': 64867, 'seconds': 8.056773662567139}
{'model': 'GRU4Rec-short-20', 'epoch': 39, 'train_loss': 0.45810151039378544, 'Hit@10': 0.6425917646877457, 'Recall@10': 0.6425917646877457, 'NDCG@10': 0.4184943292863286, 'MRR': 0.3646108844375012, 'users': 64867, 'seconds': 7.573345184326172}
{'model': 'GRU4Rec-short-20', 'epoch': 40, 'train_loss': 0.45209151288088156, 'Hit@10': 0.6444262876346987, 'Recall@10': 0.6444262876346987, 'NDCG@10': 0.41987639822448153, 'MRR': 0.3657394479537642, 'users': 64867, 'seconds': 7.288084983825684}
{'model': 'GRU4Rec-short-20', 'epoch': 41, 'train_loss': 0.4462471140879637, 'Hit@10': 0.6458291581235451, 'Recall@10': 0.6458291581235451, 'NDCG@10': 0.42067394014610043, 'MRR': 0.36625626791521176, 'users': 64867, 'seconds': 7.427960157394409}
{'model': 'GRU4Rec-short-20', 'epoch': 42, 'train_loss': 0.44159683434495606, 'Hit@10': 0.6469699539056839, 'Recall@10': 0.6469699539056839, 'NDCG@10': 0.42199309457094775, 'MRR': 0.3675176871978928, 'users': 64867, 'seconds': 7.355826139450073}
{'model': 'GRU4Rec-short-20', 'epoch': 43, 'train_loss': 0.4356385002080898, 'Hit@10': 0.6467695438358487, 'Recall@10': 0.6467695438358487, 'NDCG@10': 0.4232435206728899, 'MRR': 0.3692665459905781, 'users': 64867, 'seconds': 7.2896037101745605}
{'model': 'GRU4Rec-short-20', 'epoch': 44, 'train_loss': 0.43126921799520257, 'Hit@10': 0.6483419920760941, 'Recall@10': 0.6483419920760941, 'NDCG@10': 0.4243777216348109, 'MRR': 0.3702535573358031, 'users': 64867, 'seconds': 7.450285196304321}
{'model': 'GRU4Rec-short-20', 'epoch': 45, 'train_loss': 0.4259545078165825, 'Hit@10': 0.6485269859867113, 'Recall@10': 0.6485269859867113, 'NDCG@10': 0.424287674547584, 'MRR': 0.37004437940407586, 'users': 64867, 'seconds': 7.215186595916748}
{'model': 'GRU4Rec-short-20', 'epoch': 46, 'train_loss': 0.42118725993620354, 'Hit@10': 0.6510552360984784, 'Recall@10': 0.6510552360984784, 'NDCG@10': 0.42688668860340545, 'MRR': 0.3725393161616261, 'users': 64867, 'seconds': 7.186689138412476}
{'model': 'GRU4Rec-short-20', 'epoch': 47, 'train_loss': 0.4176289230617241, 'Hit@10': 0.6507160805956804, 'Recall@10': 0.6507160805956804, 'NDCG@10': 0.42736955993203557, 'MRR': 0.3733213371516482, 'users': 64867, 'seconds': 7.321496963500977}
{'model': 'GRU4Rec-short-20', 'epoch': 48, 'train_loss': 0.4122225514726392, 'Hit@10': 0.6526893489755963, 'Recall@10': 0.6526893489755963, 'NDCG@10': 0.4281053807733035, 'MRR': 0.3735289689529141, 'users': 64867, 'seconds': 7.353013753890991}
{'model': 'GRU4Rec-short-20', 'epoch': 49, 'train_loss': 0.40900472172513436, 'Hit@10': 0.652149783402963, 'Recall@10': 0.652149783402963, 'NDCG@10': 0.4280240795372525, 'MRR': 0.37360086027177675, 'users': 64867, 'seconds': 7.81572413444519}
{'model': 'GRU4Rec-short-20', 'epoch': 50, 'train_loss': 0.40264678879164373, 'Hit@10': 0.6540305548275702, 'Recall@10': 0.6540305548275702, 'NDCG@10': 0.42990609581515693, 'MRR': 0.3753766503816151, 'users': 64867, 'seconds': 7.297973155975342}
{'model': 'GRU4Rec-short-20', 'epoch': 51, 'train_loss': 0.3985842063730723, 'Hit@10': 0.654662617355512, 'Recall@10': 0.654662617355512, 'NDCG@10': 0.4301858837607237, 'MRR': 0.37552108889602215, 'users': 64867, 'seconds': 7.437988519668579}
{'model': 'GRU4Rec-short-20', 'epoch': 52, 'train_loss': 0.3953006465536666, 'Hit@10': 0.6566050534169917, 'Recall@10': 0.6566050534169917, 'NDCG@10': 0.43211775583142015, 'MRR': 0.37730244037032634, 'users': 64867, 'seconds': 7.274588346481323}
{'model': 'GRU4Rec-short-20', 'epoch': 53, 'train_loss': 0.3921863318445287, 'Hit@10': 0.6564046433471565, 'Recall@10': 0.6564046433471565, 'NDCG@10': 0.4322050302592738, 'MRR': 0.3775392776929798, 'users': 64867, 'seconds': 7.5273566246032715}
{'model': 'GRU4Rec-short-20', 'epoch': 54, 'train_loss': 0.38793643865834315, 'Hit@10': 0.656157984799667, 'Recall@10': 0.656157984799667, 'NDCG@10': 0.43295197362918325, 'MRR': 0.3785933936059734, 'users': 64867, 'seconds': 7.308342218399048}
{'model': 'GRU4Rec-short-20', 'epoch': 55, 'train_loss': 0.38402428452994464, 'Hit@10': 0.6576687684030401, 'Recall@10': 0.6576687684030401, 'NDCG@10': 0.43402270771202295, 'MRR': 0.379449051627227, 'users': 64867, 'seconds': 7.422473669052124}
{'model': 'GRU4Rec-short-20', 'epoch': 56, 'train_loss': 0.3808652697779903, 'Hit@10': 0.6587324833890884, 'Recall@10': 0.6587324833890884, 'NDCG@10': 0.4337749991989202, 'MRR': 0.37874309904940795, 'users': 64867, 'seconds': 7.309006214141846}
{'model': 'GRU4Rec-short-20', 'epoch': 57, 'train_loss': 0.3781640031890394, 'Hit@10': 0.6579000107913114, 'Recall@10': 0.6579000107913114, 'NDCG@10': 0.43491428279976696, 'MRR': 0.38062143626607925, 'users': 64867, 'seconds': 7.580026149749756}
{'model': 'GRU4Rec-short-20', 'epoch': 58, 'train_loss': 0.37199932616263454, 'Hit@10': 0.6603974285846425, 'Recall@10': 0.6603974285846425, 'NDCG@10': 0.43641343110665215, 'MRR': 0.38168521150512413, 'users': 64867, 'seconds': 7.32116961479187}
{'model': 'GRU4Rec-short-20', 'epoch': 59, 'train_loss': 0.3702203939589147, 'Hit@10': 0.6599657761265358, 'Recall@10': 0.6599657761265358, 'NDCG@10': 0.43582729371885187, 'MRR': 0.38102828879846834, 'users': 64867, 'seconds': 7.577703952789307}
{'model': 'GRU4Rec-short-20', 'epoch': 60, 'train_loss': 0.3678315314214587, 'Hit@10': 0.6621394545762869, 'Recall@10': 0.6621394545762869, 'NDCG@10': 0.4380632883326243, 'MRR': 0.38319053471183984, 'users': 64867, 'seconds': 7.618699312210083}
{'model': 'GRU4Rec-short-20', 'epoch': 61, 'train_loss': 0.36365034634821647, 'Hit@10': 0.6621857030539411, 'Recall@10': 0.6621857030539411, 'NDCG@10': 0.43787260145695517, 'MRR': 0.3828250212329196, 'users': 64867, 'seconds': 7.301562547683716}
{'model': 'GRU4Rec-short-20', 'epoch': 62, 'train_loss': 0.36198428367776914, 'Hit@10': 0.6617848829142707, 'Recall@10': 0.6617848829142707, 'NDCG@10': 0.4377169524020226, 'MRR': 0.3828123272134179, 'users': 64867, 'seconds': 7.387606859207153}
{'model': 'GRU4Rec-short-20', 'epoch': 63, 'train_loss': 0.35746012422286966, 'Hit@10': 0.6635885735427876, 'Recall@10': 0.6635885735427876, 'NDCG@10': 0.43956264800321093, 'MRR': 0.3846035323563455, 'users': 64867, 'seconds': 7.303416013717651}
{'model': 'GRU4Rec-short-20', 'epoch': 64, 'train_loss': 0.3569566478056653, 'Hit@10': 0.6642360522299474, 'Recall@10': 0.6642360522299474, 'NDCG@10': 0.44013659360704044, 'MRR': 0.38511452376252564, 'users': 64867, 'seconds': 7.4753639698028564}
{'model': 'GRU4Rec-short-20', 'epoch': 65, 'train_loss': 0.3512685516068791, 'Hit@10': 0.6641589714338569, 'Recall@10': 0.6641589714338569, 'NDCG@10': 0.4404476413831987, 'MRR': 0.3855450662584136, 'users': 64867, 'seconds': 7.427831649780273}
{'model': 'GRU4Rec-short-20', 'epoch': 66, 'train_loss': 0.3489199725209817, 'Hit@10': 0.6644056299813464, 'Recall@10': 0.6644056299813464, 'NDCG@10': 0.44068967679666593, 'MRR': 0.3857418890124245, 'users': 64867, 'seconds': 7.218950033187866}
{'model': 'GRU4Rec-short-20', 'epoch': 67, 'train_loss': 0.34624447065753183, 'Hit@10': 0.6653922641713044, 'Recall@10': 0.6653922641713044, 'NDCG@10': 0.4411736486385802, 'MRR': 0.38607263041915957, 'users': 64867, 'seconds': 7.295154571533203}
{'model': 'GRU4Rec-short-20', 'epoch': 68, 'train_loss': 0.34330038132312196, 'Hit@10': 0.6657314196741024, 'Recall@10': 0.6657314196741024, 'NDCG@10': 0.4415386336587421, 'MRR': 0.38637432509899244, 'users': 64867, 'seconds': 7.343683481216431}
{'model': 'GRU4Rec-short-20', 'epoch': 69, 'train_loss': 0.34143770387297784, 'Hit@10': 0.6651456056238149, 'Recall@10': 0.6651456056238149, 'NDCG@10': 0.4418380659780332, 'MRR': 0.3870184367017138, 'users': 64867, 'seconds': 7.522567272186279}
{'model': 'GRU4Rec-short-20', 'epoch': 70, 'train_loss': 0.339661058215146, 'Hit@10': 0.6663788983612623, 'Recall@10': 0.6663788983612623, 'NDCG@10': 0.44257369923484075, 'MRR': 0.3875378053638441, 'users': 64867, 'seconds': 7.49381685256958}
{'model': 'GRU4Rec-short-20', 'epoch': 71, 'train_loss': 0.3363602054062431, 'Hit@10': 0.667843433486981, 'Recall@10': 0.667843433486981, 'NDCG@10': 0.44310154222413567, 'MRR': 0.3877324152401451, 'users': 64867, 'seconds': 7.703092098236084}
{'model': 'GRU4Rec-short-20', 'epoch': 72, 'train_loss': 0.3357438737213882, 'Hit@10': 0.6662709852467357, 'Recall@10': 0.6662709852467357, 'NDCG@10': 0.4425882317681923, 'MRR': 0.3876000962711797, 'users': 64867, 'seconds': 7.306680917739868}
{'model': 'GRU4Rec-short-20', 'epoch': 73, 'train_loss': 0.3326982734472281, 'Hit@10': 0.6675505264618373, 'Recall@10': 0.6675505264618373, 'NDCG@10': 0.44394311850089, 'MRR': 0.3888694466211644, 'users': 64867, 'seconds': 7.278545379638672}
{'model': 'GRU4Rec-short-20', 'epoch': 74, 'train_loss': 0.3306184085051487, 'Hit@10': 0.6677971850093267, 'Recall@10': 0.6677971850093267, 'NDCG@10': 0.44424892609436956, 'MRR': 0.38914397093685715, 'users': 64867, 'seconds': 7.325360059738159}
{'model': 'GRU4Rec-short-20', 'epoch': 75, 'train_loss': 0.32822951838700826, 'Hit@10': 0.6692617201350456, 'Recall@10': 0.6692617201350456, 'NDCG@10': 0.44531014935643526, 'MRR': 0.390015901006722, 'users': 64867, 'seconds': 7.447866678237915}
{'model': 'GRU4Rec-short-20', 'epoch': 76, 'train_loss': 0.3271025666495518, 'Hit@10': 0.6685217444925772, 'Recall@10': 0.6685217444925772, 'NDCG@10': 0.4455226087650191, 'MRR': 0.3905829169711966, 'users': 64867, 'seconds': 7.337792634963989}
{'model': 'GRU4Rec-short-20', 'epoch': 77, 'train_loss': 0.3229044989611284, 'Hit@10': 0.6691229747020827, 'Recall@10': 0.6691229747020827, 'NDCG@10': 0.44492807800705125, 'MRR': 0.38960990052525685, 'users': 64867, 'seconds': 7.3478662967681885}
{'model': 'GRU4Rec-short-20', 'epoch': 78, 'train_loss': 0.32054953763337024, 'Hit@10': 0.66866048992554, 'Recall@10': 0.66866048992554, 'NDCG@10': 0.4452431676672665, 'MRR': 0.3902142542079543, 'users': 64867, 'seconds': 7.156599521636963}
{'model': 'GRU4Rec-short-20', 'epoch': 79, 'train_loss': 0.3185519389685515, 'Hit@10': 0.6707725037384186, 'Recall@10': 0.6707725037384186, 'NDCG@10': 0.4456756434219461, 'MRR': 0.3899640259874479, 'users': 64867, 'seconds': 7.243448734283447}
{'model': 'GRU4Rec-short-20', 'epoch': 80, 'train_loss': 0.3171557893996989, 'Hit@10': 0.6694467140456627, 'Recall@10': 0.6694467140456627, 'NDCG@10': 0.4454858889674576, 'MRR': 0.39022055840201025, 'users': 64867, 'seconds': 7.393190860748291}
{'model': 'GRU4Rec-short-20', 'epoch': 81, 'train_loss': 0.31457033718463057, 'Hit@10': 0.6697704533892426, 'Recall@10': 0.6697704533892426, 'NDCG@10': 0.4464628401942487, 'MRR': 0.3913662433365562, 'users': 64867, 'seconds': 7.263131380081177}

   seed  epoch   NDCG@10    Hit@10       MRR
0  2026     99  0.455477  0.677725  0.400238
1  2027    100  0.453646  0.675582  0.398623
2  2028    100  0.454071  0.676723  0.398748

       NDCG@10    Hit@10       MRR
mean  0.454398  0.676677  0.399203
std   0.000958  0.001072  0.000898

In [18]:
def restore_selected(trial):
    if trial["architecture"] == "SASRec":
        selected = SASRec(NUM_ITEMS, trial["max_len"], trial["hidden_dim"], trial["num_blocks"], trial["num_heads"], trial["dropout"]).to(DEVICE)
        pad_context = left_pad_context
    else:
        selected = GRU4Rec(NUM_ITEMS, trial["max_len"], trial["hidden_dim"], trial["num_layers"], trial["dropout"]).to(DEVICE)
        pad_context = right_pad_context
    selected.load_state_dict(trial["state"])
    return selected, pad_context


best_sasrec = max(sasrec_trials, key=lambda trial: trial["validation"][f"NDCG@{CFG.top_k}"])
best_gru4rec = max(gru4rec_trials, key=lambda trial: trial["validation"][f"NDCG@{CFG.top_k}"])
selected_trials = [best_sasrec, best_gru4rec]
neural_rows, selected_models = [], {}
for trial in selected_trials:
    selected_model, pad_context = restore_selected(trial)
    selected_models[trial["architecture"]] = selected_model
    val_metrics = evaluate_neural(selected_model, val_contexts, val_targets, val_negatives, trial["max_len"], pad_context, CFG.eval_batch_size, CFG.top_k)
    test_metrics = evaluate_neural(selected_model, test_contexts, test_targets, test_negatives, trial["max_len"], pad_context, CFG.eval_batch_size, CFG.top_k)
    neural_rows.extend([{"model": trial["name"], "split": "validation", **val_metrics}, {"model": trial["name"], "split": "test", **test_metrics}])
results_df = pd.concat([baseline_results, pd.DataFrame(neural_rows)], ignore_index=True)
history_df, best_state = best_sasrec["history"], best_sasrec["state"]
# GRU4Rec is the selected production model: it wins validation selection and is the
# only neural model used by the qualitative and full-catalogue inference cells below.
final_trial, final_model, final_pad_context = best_gru4rec, selected_models["GRU4Rec"], right_pad_context
results_df.sort_values(["split", f"NDCG@{CFG.top_k}"], ascending=[True, False])

C:\Users\al\AppData\Local\Temp\ipykernel_45112\1547733667.py:26: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.encoder = nn.TransformerEncoder(layer, num_layers=num_blocks)

,model,split,Hit@10,Recall@10,NDCG@10,MRR,users
7,GRU4Rec-short-20,test,0.640742,0.640742,0.423697,0.371434,64867
3,Markov-1,test,0.417115,0.417115,0.288026,0.265202,64867
1,Popularity,test,0.375121,0.375121,0.232436,0.206891,64867
5,SASRec-short-20,test,0.166741,0.166741,0.094416,0.094408,64867
6,GRU4Rec-short-20,validation,0.677725,0.677725,0.455477,0.400238,64867
2,Markov-1,validation,0.456827,0.456827,0.320822,0.295560,64867
0,Popularity,validation,0.405645,0.405645,0.253269,0.224836,64867
4,SASRec-short-20,validation,0.169824,0.169824,0.098172,0.098114,64867

### Presentation-only checkpoint restore

Use this cell after the data, baseline, and GRU definition cells when presenting existing results. It restores the validation-selected GRU4Rec checkpoint without rerunning neural training, then refreshes the fixed-protocol comparison and the ensemble cells below. Full training and the mixed-negative ablation remain in the preceding tuning section.

In [10]:
# Restore the saved validation-selected GRU4Rec for a fast, reproducible presentation run.
checkpoint_path = Path("outputs/gru4rec_best.pt")
if not checkpoint_path.exists():
    raise FileNotFoundError("Run the tuning section once before using presentation-only restore.")
checkpoint = torch.load(checkpoint_path, map_location=DEVICE, weights_only=False)
final_trial = checkpoint["config"]
final_model = GRU4Rec(NUM_ITEMS, final_trial["max_len"], final_trial["hidden_dim"], final_trial["num_layers"], final_trial["dropout"]).to(DEVICE)
final_model.load_state_dict(checkpoint["model_state_dict"])
final_pad_context = right_pad_context
results_path = Path("outputs/candidate_set_results.csv")
results_df = pd.read_csv(results_path) if results_path.exists() else baseline_results.copy()
# The ensemble cell appends a newly evaluated row, so remove any stale copy first.
results_df = results_df[~results_df["model"].astype(str).str.startswith("GRU4Rec-Markov")].copy()
display(results_df.sort_values(["split", f"NDCG@{CFG.top_k}"], ascending=[True, False]))

,model,split,Hit@10,Recall@10,NDCG@10,MRR,users,Precision@10,CandidateAccuracy@10
7,GRU4Rec-short-20,test,0.640742,0.640742,0.423697,0.371434,64867.0,0.064074,0.907334
3,Markov-1,test,0.417115,0.417115,0.288026,0.265202,64867.0,0.041712,0.905120
1,Popularity,test,0.375121,0.375121,0.232436,0.206891,64867.0,0.037512,0.904704
5,SASRec-short-20,test,0.166741,0.166741,0.094416,0.094408,64867.0,0.016674,0.902641
6,GRU4Rec-short-20,validation,0.677725,0.677725,0.455477,0.400238,64867.0,0.067773,0.907700
2,Markov-1,validation,0.456827,0.456827,0.320822,0.295560,64867.0,0.045683,0.905513
0,Popularity,validation,0.405645,0.405645,0.253269,0.224836,64867.0,0.040565,0.905006
4,SASRec-short-20,validation,0.169824,0.169824,0.098172,0.098114,64867.0,0.016982,0.902672

## 11. Low-complexity sequential refinement: GRU4Rec-Markov ensemble

The GRU captures a multi-item sequential state, while Markov-1 retains a direct next-item transition signal from the final item. Candidate scores are standardised per user and the GRU weight is selected only by validation NDCG@10. This adds no trainable parameters and only one sparse transition lookup per candidate at inference. The test split is evaluated once after selection.

In [11]:
def standardise_candidate_scores(scores: np.ndarray) -> np.ndarray:
    mean = scores.mean(axis=1, keepdims=True)
    std = scores.std(axis=1, keepdims=True)
    return (scores - mean) / np.maximum(std, 1e-8)


@torch.no_grad()
def evaluate_gru_markov_ensemble(model, contexts, targets, negatives, max_len: int, gru_weight: float, batch_size: int = 512, k: int = 10):
    model.eval()
    ranks = []
    users = sorted(targets)
    for start in range(0, len(users), batch_size):
        batch_users = users[start:start + batch_size]
        inputs = np.stack([right_pad_context(contexts[user], max_len) for user in batch_users])
        candidates = np.asarray([[targets[user], *negatives[user]] for user in batch_users], dtype=np.int64)
        gru_scores = model.score_candidates(torch.as_tensor(inputs, device=DEVICE), torch.as_tensor(candidates + 1, device=DEVICE)).cpu().numpy()
        markov_scores = np.vstack([markov_score(user, contexts[user], candidates[row]) for row, user in enumerate(batch_users)])
        scores = gru_weight * standardise_candidate_scores(gru_scores) + (1.0 - gru_weight) * standardise_candidate_scores(markov_scores)
        ranks.extend(rank_from_scores(user, candidates[row], scores[row], CFG.seed) for row, user in enumerate(batch_users))
    return summarise_ranks(ranks, k)


ENSEMBLE_GRU_WEIGHTS = (0.50, 0.65, 0.75, 0.85, 1.00)
ensemble_validation_rows = []
for weight in ENSEMBLE_GRU_WEIGHTS:
    metrics = evaluate_gru_markov_ensemble(final_model, val_contexts, val_targets, val_negatives, final_trial["max_len"], weight, CFG.eval_batch_size, CFG.top_k)
    ensemble_validation_rows.append({"gru_weight": weight, "markov_weight": 1.0 - weight, **metrics})
ensemble_validation_df = pd.DataFrame(ensemble_validation_rows).sort_values(f"NDCG@{CFG.top_k}", ascending=False)
best_ensemble = ensemble_validation_df.iloc[0].to_dict()
best_ensemble_test = evaluate_gru_markov_ensemble(final_model, test_contexts, test_targets, test_negatives, final_trial["max_len"], best_ensemble["gru_weight"], CFG.eval_batch_size, CFG.top_k)
ensemble_name = f"GRU4Rec-Markov (GRU={best_ensemble['gru_weight']:.2f})"
results_df = pd.concat([results_df, pd.DataFrame([
    {"model": ensemble_name, "split": "validation", **{key: value for key, value in best_ensemble.items() if key not in {"gru_weight", "markov_weight"}}},
    {"model": ensemble_name, "split": "test", **best_ensemble_test},
])], ignore_index=True)
display(ensemble_validation_df)
results_df.sort_values(["split", f"NDCG@{CFG.top_k}"], ascending=[True, False])

,gru_weight,markov_weight,Hit@10,Recall@10,Precision@10,CandidateAccuracy@10,NDCG@10,MRR,users
3,0.85,0.15,0.676708,0.676708,0.067671,0.907690,0.474027,0.424634,64867
2,0.75,0.25,0.661045,0.661045,0.066104,0.907535,0.460903,0.412848,64867
4,1.00,0.00,0.677725,0.677725,0.067773,0.907700,0.455477,0.400238,64867
1,0.65,0.35,0.637998,0.637998,0.063800,0.907307,0.440750,0.394364,64867
0,0.50,0.50,0.592690,0.592690,0.059269,0.906858,0.406686,0.365021,64867

,model,split,Hit@10,Recall@10,NDCG@10,MRR,users,Precision@10,CandidateAccuracy@10
9,GRU4Rec-Markov (GRU=0.85),test,0.634776,0.634776,0.437167,0.390772,64867.0,0.063478,0.907275
7,GRU4Rec-short-20,test,0.640742,0.640742,0.423697,0.371434,64867.0,0.064074,0.907334
3,Markov-1,test,0.417115,0.417115,0.288026,0.265202,64867.0,0.041712,0.905120
1,Popularity,test,0.375121,0.375121,0.232436,0.206891,64867.0,0.037512,0.904704
5,SASRec-short-20,test,0.166741,0.166741,0.094416,0.094408,64867.0,0.016674,0.902641
8,GRU4Rec-Markov (GRU=0.85),validation,0.676708,0.676708,0.474027,0.424634,64867.0,0.067671,0.907690
6,GRU4Rec-short-20,validation,0.677725,0.677725,0.455477,0.400238,64867.0,0.067773,0.907700
2,Markov-1,validation,0.456827,0.456827,0.320822,0.295560,64867.0,0.045683,0.905513
0,Popularity,validation,0.405645,0.405645,0.253269,0.224836,64867.0,0.040565,0.905006
4,SASRec-short-20,validation,0.169824,0.169824,0.098172,0.098114,64867.0,0.016982,0.902672

In [12]:
# Optional reproducibility outputs.
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
results_df.to_csv(OUTPUT_DIR / "candidate_set_results.csv", index=False)
if "history_df" in globals(): history_df.to_csv(OUTPUT_DIR / "sasrec_training_history.csv", index=False)
if "best_gru4rec" in globals(): best_gru4rec["history"].to_csv(OUTPUT_DIR / "gru4rec_training_history.csv", index=False)
if "tuning_validation_df" in globals(): tuning_validation_df.to_csv(OUTPUT_DIR / "neural_tuning_validation_results.csv", index=False)
if "seed_stability_df" in globals(): seed_stability_df.to_csv(OUTPUT_DIR / "gru4rec_seed_stability.csv", index=False)
if "ensemble_validation_df" in globals(): ensemble_validation_df.to_csv(OUTPUT_DIR / "gru_markov_ensemble_validation.csv", index=False)
if "best_state" in globals() and "best_sasrec" in globals(): torch.save(
    {
        "model_state_dict": best_state,
        "config": {key: value for key, value in best_sasrec.items() if key not in {"history", "state", "validation"}},
        "num_items": NUM_ITEMS,
        "raw_to_model_item_offset": 1,
    },
    OUTPUT_DIR / "sasrec_lite_best.pt",
)
if "best_gru4rec" in globals(): torch.save(
    {
        "model_state_dict": best_gru4rec["state"],
        "config": {key: value for key, value in best_gru4rec.items() if key not in {"history", "state", "validation", "dataset_cls"}},
        "num_items": NUM_ITEMS,
        "raw_to_model_item_offset": 1,
    },
    OUTPUT_DIR / "gru4rec_best.pt",
)
print("saved outputs to", OUTPUT_DIR.resolve())

saved outputs to D:\unsw\COMP9727\proj2\outputs

## 11. Optional qualitative inspection with metadata

This section is for interpretation only. Metadata does not enter SASRec training. It displays the target and the model's top-ranked candidates for selected users, which can reveal popularity bias, repeated authors/categories, or implausible recommendations that aggregate metrics hide.

In [12]:
def infer_metadata_item_col(df: pd.DataFrame) -> str:
    return choose_col(df, ["item_idx", "item_id", "item"], "metadata item")


@torch.no_grad()
def inspect_user(user: int, split: str = "test", top_n: int = 10) -> pd.DataFrame:
    if split == "validation":
        contexts, targets, negatives = val_contexts, val_targets, val_negatives
    elif split == "test":
        contexts, targets, negatives = test_contexts, test_targets, test_negatives
    else:
        raise ValueError("split must be 'validation' or 'test'")
    candidates = np.asarray([targets[user], *negatives[user]], dtype=np.int64)
    inputs = torch.as_tensor(final_pad_context(contexts[user], final_trial["max_len"])[None, :], device=DEVICE)
    candidate_tensor = torch.as_tensor(candidates[None, :] + 1, device=DEVICE)
    scores = final_model.score_candidates(inputs, candidate_tensor)[0].cpu().numpy()
    order = np.argsort(-scores, kind="stable")[:top_n]
    ranked = pd.DataFrame({
        "rank": np.arange(1, len(order) + 1),
        "item_idx": candidates[order],
        "score": scores[order],
        "is_target": candidates[order] == targets[user],
    })
    metadata_item_col = infer_metadata_item_col(item_metadata_df)
    metadata = item_metadata_df.rename(columns={metadata_item_col: "item_idx"})
    keep = [c for c in ["item_idx", "title", "author", "categories"] if c in metadata.columns]
    return ranked.merge(metadata[keep], on="item_idx", how="left")


# Example after training:
# inspect_user(user=sorted(test_targets)[0], split="test", top_n=10)

## 12. Category-aware Top-10 inference and catalogue behaviour

The final GRU4Rec scores unseen catalogue items. Candidate filtering retains books sharing a user-profile category; MMR reranking then discourages repeated authors and highly overlapping category labels. These presentation-time controls do not affect the fixed-candidate accuracy evaluation.

In [13]:
metadata_item_col = infer_metadata_item_col(item_metadata_df)
metadata_for_ranking = item_metadata_df.rename(columns={metadata_item_col: "item_idx"}).set_index("item_idx", drop=True)


def category_set(item: int) -> frozenset:
    if item not in metadata_for_ranking.index:
        return frozenset()
    value = metadata_for_ranking.at[item, "categories"] if "categories" in metadata_for_ranking.columns else ""
    return frozenset(part.strip() for part in str(value).split(";") if part.strip())


ITEM_CATEGORIES = {item: category_set(item) for item in range(NUM_ITEMS)}
ITEM_AUTHORS = {item: str(metadata_for_ranking.at[item, "author"]).strip() if item in metadata_for_ranking.index and "author" in metadata_for_ranking.columns else "" for item in range(NUM_ITEMS)}


def user_category_profile(context: Sequence[int], max_categories: int = 5) -> set:
    counts = Counter(category for item in context for category in ITEM_CATEGORIES[item])
    return {category for category, _ in counts.most_common(max_categories)}


@torch.no_grad()
def score_unseen_catalogue(user: int, context: Optional[Sequence[int]] = None, category_filter: bool = False, candidate_batch_size: int = 4096) -> pd.DataFrame:
    context = list(train_sequences[user] if context is None else context)
    if not context:
        raise ValueError("At least one observed item is required")
    seen, profile = set(context), user_category_profile(context)
    candidates = np.fromiter((item for item in range(NUM_ITEMS) if item not in seen and (not category_filter or not profile or bool(ITEM_CATEGORIES[item] & profile))), dtype=np.int64)
    if len(candidates) == 0:
        raise RuntimeError("No unseen candidates after filtering")
    inputs = torch.as_tensor(final_pad_context(context, final_trial["max_len"])[None, :], device=DEVICE)
    final_model.eval()
    scores = []
    for start in range(0, len(candidates), candidate_batch_size):
        batch = candidates[start:start + candidate_batch_size]
        scores.append(final_model.score_candidates(inputs, torch.as_tensor(batch[None, :] + 1, device=DEVICE))[0].cpu().numpy())
    ranked = pd.DataFrame({"item_idx": candidates, "score": np.concatenate(scores)})
    return ranked.sort_values("score", ascending=False, kind="stable").reset_index(drop=True)


def item_similarity(left: int, right: int) -> float:
    left_categories, right_categories = ITEM_CATEGORIES[left], ITEM_CATEGORIES[right]
    category_similarity = len(left_categories & right_categories) / max(len(left_categories | right_categories), 1)
    author_similarity = float(bool(ITEM_AUTHORS[left]) and ITEM_AUTHORS[left] == ITEM_AUTHORS[right])
    return max(category_similarity, author_similarity)


def mmr_rerank(scored_items: pd.DataFrame, top_k: int = 10, pool_size: int = 200, relevance_weight: float = 0.85) -> pd.DataFrame:
    pool = scored_items.head(pool_size).copy().reset_index(drop=True)
    score_range = max(pool.score.max() - pool.score.min(), 1e-12)
    pool["relevance"] = (pool.score - pool.score.min()) / score_range
    selected = []
    while len(selected) < min(top_k, len(pool)):
        remaining = [index for index in pool.index if index not in selected]
        choice = max(remaining, key=lambda index: relevance_weight * pool.at[index, "relevance"] - (1 - relevance_weight) * max((item_similarity(int(pool.at[index, "item_idx"]), int(pool.at[chosen, "item_idx"])) for chosen in selected), default=0.0))
        selected.append(choice)
    result = pool.loc[selected, ["item_idx", "score"]].copy()
    result.insert(0, "rank", np.arange(1, len(result) + 1))
    return result


def recommend_top_k(user: int, context: Optional[Sequence[int]] = None, top_k: int = 10, category_filter: bool = True, mmr: bool = True) -> pd.DataFrame:
    scored = score_unseen_catalogue(user, context, category_filter)
    ranked = mmr_rerank(scored, top_k=top_k) if mmr else scored.head(top_k).assign(rank=lambda frame: np.arange(1, len(frame) + 1))[["rank", "item_idx", "score"]]
    keep = [column for column in ["title", "author", "categories", "average_rating", "rating_number"] if column in metadata_for_ranking.columns]
    return ranked.merge(metadata_for_ranking[keep].reset_index(), on="item_idx", how="left")


def recommendation_diagnostics(users: Sequence[int], top_k: int = 10) -> pd.DataFrame:
    catalogue_items, rows = set(), []
    total_popularity = popularity.sum()
    for user in users:
        recommendations = recommend_top_k(user, top_k=top_k)
        items = recommendations.item_idx.astype(int).tolist()
        catalogue_items.update(items)
        similarities = [item_similarity(left, right) for position, left in enumerate(items) for right in items[position + 1:]]
        novelty = np.mean([-np.log2((popularity[item] + 1) / (total_popularity + NUM_ITEMS)) for item in items])
        rows.append({"user_idx": user, "novelty": novelty, "intra_list_diversity": 1 - np.mean(similarities) if similarities else 0.0, "avg_train_popularity": float(np.mean(popularity[items]))})
    return pd.DataFrame(rows), {"users": len(users), "catalogue_coverage": len(catalogue_items) / NUM_ITEMS, "unique_recommended_items": len(catalogue_items)}


# Example: recommend_top_k(user=0)
# diagnostics_df, catalogue_metrics = recommendation_diagnostics(sorted(train_sequences)[:100])

In [14]:
# Deterministic system-level diagnostics on a manageable user sample.
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
diagnostic_rng = np.random.default_rng(CFG.seed)
diagnostic_users = diagnostic_rng.choice(np.asarray(sorted(train_sequences)), size=min(50, len(train_sequences)), replace=False).tolist()
catalogue_diagnostics_df, catalogue_metrics = recommendation_diagnostics(diagnostic_users)
catalogue_diagnostics_df.to_csv(OUTPUT_DIR / "gru4rec_catalogue_diagnostics.csv", index=False)
with open(OUTPUT_DIR / "gru4rec_catalogue_metrics.json", "w", encoding="utf-8") as handle:
    json.dump(catalogue_metrics, handle, indent=2)
print("catalogue metrics:", catalogue_metrics)
display(catalogue_diagnostics_df.describe())

catalogue metrics: {'users': 50, 'catalogue_coverage': 0.004623595091119254, 'unique_recommended_items': 376}

           user_idx    novelty  intra_list_diversity  avg_train_popularity
count     50.000000  50.000000             50.000000             50.000000
mean   31745.180000  13.682728              0.284259            146.628000
std    17928.297753   1.639647              0.228892            127.627652
min      832.000000  11.158217              0.000000              7.700000
25%    17678.000000  12.091477              0.000000             34.725000
50%    30252.000000  13.589245              0.259259             87.200000
75%    46484.750000  15.231056              0.508333            254.350000
max    62696.000000  16.916948              0.688889            434.900000

## 12. Report checklist and interpretation boundaries

Record the following in the project report:

- preprocessing threshold (`rating >= 4`), 5-core procedure, chronological leave-two-out split, and fixed negative sampling, copied exactly from the JSON files;
- dataset counts and sequence-length distribution after preprocessing;
- all model hyperparameters, random seed, maximum epochs, patience, and the epoch selected by validation NDCG@10;
- Popularity, Markov-1, and SASRec results under the same 101-item candidate sets;
- the fact that Hit@10 equals Recall@10 because there is exactly one relevant item;
- test context includes the validation item, while neither held-out test items nor candidate negatives enter training;
- limitations: sampled-negative metrics are not full-catalogue metrics, offline logs reflect exposure/selection bias, short histories restrict the advantage of deeper attention, and results may vary across seeds.

A defensible conclusion is conditional: SASRec provides evidence of value from attention only if it beats the sequential Markov baseline consistently on validation and the untouched test split. Beating popularity alone is insufficient to isolate the benefit of attention.